create table if not exists public.estadisticas_logros (
  id bigint generated by default as identity primary key,
  usuario text not null,
  juego text not null,
  completados integer not null default 0,
  completados_sin_errores integer not null default 0,
  racha_completados_actual integer not null default 0,
  mejor_racha_completados integer not null default 0,
  racha_sin_errores_actual integer not null default 0,
  mejor_racha_sin_errores integer not null default 0,
  mejor_tiempo integer,
  tiempo_jugado_total integer not null default 0,
  racha_tiempo_jugado_actual integer not null default 0,
  mejor_racha_tiempo_jugado integer not null default 0,
  torneos_participados integer not null default 0,
  mejor_posicion_torneo integer,
  victorias_torneos integer not null default 0,
  racha_top10_torneos_actual integer not null default 0,
  mejor_racha_top10_torneos integer not null default 0,
  victorias_sin_errores integer not null default 0,
  ultima_posicion_torneo integer,
  top15_torneos integer not null default 0,
  cuartos_lugares integer not null default 0,
  posiciones_mejoradas integer not null default 0,
  max_posiciones_subidas integer not null default 0,
  mejores_historicas_superadas integer not null default 0,
  jugadores_mejor_rankeados_superados integer not null default 0,
  max_jugadores_mejor_rankeados_superados integer not null default 0,
  torneos_mismo_dia_fecha text,
  torneos_mismo_dia_actual integer not null default 0,
  mejor_torneos_mismo_dia integer not null default 0,
  memoria_errores_total integer not null default 0,
  memoria_min_errores_partida integer,
  memoria_max_errores_partida integer not null default 0,
  memoria_mejor_racha_pares integer not null default 0,
  memoria_mejor_racha_fallos integer not null default 0,
  memoria_pares_antes_1min integer not null default 0,
  memoria_max_intentos_partida integer not null default 0,
  memoria_mejor_movimientos integer,
  memoria_mejor_tiempo_sin_errores integer,
  memoria_menos_20_movimientos integer not null default 0,
  memoria_mejoras_tiempo integer not null default 0,
  memoria_fallo_ultimo_par integer not null default 0,
  memoria_acierto_tras_5_fallos integer not null default 0,
  memoria_par_menos_2s integer not null default 0,
  memoria_par_menos_20s integer not null default 0,
  memoria_acierto_tras_2_fallos integer not null default 0,
  memoria_par_sin_ver_previo integer not null default 0,
  memoria_sin_repetir_error_par integer not null default 0,
  memoria_partidas_ventana_inicio text,
  memoria_partidas_ventana_actual integer not null default 0,
  memoria_mejor_partidas_10min integer not null default 0,
  memoria_partidas_ventana_15_inicio text,
  memoria_partidas_ventana_15_actual integer not null default 0,
  memoria_mejor_partidas_15min integer not null default 0,
  memoria_primer_movimiento_par integer not null default 0,
  memoria_lineal integer not null default 0,
  memoria_sin_patron_repetido integer not null default 0,
  memoria_anticipacion integer not null default 0,
  memoria_sin_cartas_falladas_repetidas integer not null default 0,
  memoria_inicio_4_pares integer not null default 0,
  memoria_final_4_pares integer not null default 0,
  matematicas_total_correctas integer not null default 0,
  matematicas_sesiones_sin_errores integer not null default 0,
  matematicas_ejercicios_menos_15s integer not null default 0,
  matematicas_ejercicios_menos_14s integer not null default 0,
  matematicas_ejercicios_menos_13s integer not null default 0,
  matematicas_ejercicios_menos_12s integer not null default 0,
  matematicas_ejercicios_menos_11s integer not null default 0,
  matematicas_ejercicios_menos_10s integer not null default 0,
  matematicas_ejercicios_menos_9s integer not null default 0,
  matematicas_ejercicios_menos_8s integer not null default 0,
  matematicas_ejercicios_menos_7s integer not null default 0,
  matematicas_ejercicios_menos_6s integer not null default 0,
  matematicas_ejercicios_menos_5s integer not null default 0,
  matematicas_ejercicios_menos_4s integer not null default 0,
  matematicas_ejercicios_menos_3_5s integer not null default 0,
  matematicas_ejercicios_menos_3s integer not null default 0,
  matematicas_ejercicios_menos_2_5s integer not null default 0,
  matematicas_ejercicios_menos_2s integer not null default 0,
  matematicas_ejercicios_menos_1_8s integer not null default 0,
  matematicas_ejercicios_menos_1_5s integer not null default 0,
  matematicas_ejercicios_menos_1_2s integer not null default 0,
  matematicas_ejercicios_menos_1s integer not null default 0,
  matematicas_ejercicios_menos_0_8s integer not null default 0,
  matematicas_mejor_racha_correctas integer not null default 0,
  matematicas_mejor_racha_3s integer not null default 0,
  matematicas_mejor_racha_5s integer not null default 0,
  matematicas_mejor_correctas_60s integer not null default 0,
  ultimo_tiempo integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (usuario, juego)
);

alter table public.estadisticas_logros
add column if not exists racha_completados_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_racha_completados integer not null default 0;

alter table public.estadisticas_logros
add column if not exists tiempo_jugado_total integer not null default 0;

alter table public.estadisticas_logros
add column if not exists racha_tiempo_jugado_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_racha_tiempo_jugado integer not null default 0;

alter table public.estadisticas_logros
add column if not exists torneos_participados integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_posicion_torneo integer;

alter table public.estadisticas_logros
add column if not exists victorias_torneos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists racha_top10_torneos_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_racha_top10_torneos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists victorias_sin_errores integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ultima_posicion_torneo integer;

alter table public.estadisticas_logros
add column if not exists top15_torneos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists cuartos_lugares integer not null default 0;

alter table public.estadisticas_logros
add column if not exists posiciones_mejoradas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists max_posiciones_subidas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejores_historicas_superadas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists jugadores_mejor_rankeados_superados integer not null default 0;

alter table public.estadisticas_logros
add column if not exists max_jugadores_mejor_rankeados_superados integer not null default 0;

alter table public.estadisticas_logros
add column if not exists torneos_mismo_dia_fecha text;

alter table public.estadisticas_logros
add column if not exists torneos_mismo_dia_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_torneos_mismo_dia integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_errores_total integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_min_errores_partida integer;

alter table public.estadisticas_logros
add column if not exists memoria_max_errores_partida integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_racha_pares integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_racha_fallos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_pares_antes_1min integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_max_intentos_partida integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_movimientos integer;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_tiempo_sin_errores integer;

alter table public.estadisticas_logros
add column if not exists memoria_menos_20_movimientos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejoras_tiempo integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_fallo_ultimo_par integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_acierto_tras_5_fallos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_par_menos_2s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_par_menos_20s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_acierto_tras_2_fallos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_par_sin_ver_previo integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_sin_repetir_error_par integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_partidas_ventana_inicio text;

alter table public.estadisticas_logros
add column if not exists memoria_partidas_ventana_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_partidas_10min integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_partidas_ventana_15_inicio text;

alter table public.estadisticas_logros
add column if not exists memoria_partidas_ventana_15_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_partidas_15min integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_primer_movimiento_par integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_lineal integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_sin_patron_repetido integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_anticipacion integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_sin_cartas_falladas_repetidas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_inicio_4_pares integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_final_4_pares integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_total_correctas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_sesiones_sin_errores integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_15s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_14s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_13s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_12s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_11s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_10s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_9s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_8s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_7s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_6s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_5s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_4s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_3_5s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_3s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_2_5s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_2s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_1_8s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_1_5s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_1_2s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_1s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_0_8s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_mejor_racha_correctas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_mejor_racha_3s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_mejor_racha_5s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_mejor_correctas_60s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ultimo_tiempo integer;

create index if not exists estadisticas_logros_usuario_idx
on public.estadisticas_logros (usuario);

create index if not exists estadisticas_logros_juego_idx
on public.estadisticas_logros (juego);

create table if not exists public.temporadas_nivel (
  id text primary key,
  nombre text not null,
  activa boolean not null default false,
  fecha_inicio timestamptz not null default now(),
  fecha_fin timestamptz,
  created_at timestamptz not null default now()
);

insert into public.temporadas_nivel (id, nombre, activa)
values ('temporada-actual', 'Temporada actual', true)
on conflict (id) do nothing;

create table if not exists public.progreso_nivel (
  usuario_id text primary key,
  temporada_id text not null default 'temporada-actual' references public.temporadas_nivel(id),
  xp integer not null default 0 check (xp >= 0),
  nivel integer not null default 1 check (nivel between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recompensas_nivel (
  id bigint generated by default as identity primary key,
  nivel integer not null check (nivel between 1 and 100),
  tipo text not null check (tipo in ('titulo', 'medalla', 'estilo', 'logro', 'xp_bonus')),
  valor text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (nivel, tipo, valor)
);

create table if not exists public.historial_xp (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  accion text not null,
  accion_key text,
  xp_ganado integer not null check (xp_ganado > 0),
  detalle jsonb not null default '{}'::jsonb,
  fecha timestamptz not null default now(),
  unique (usuario_id, accion_key)
);

create table if not exists public.recompensas_desbloqueadas (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  nivel integer not null check (nivel between 1 and 100),
  recompensa_id bigint references public.recompensas_nivel(id),
  tipo text not null,
  valor text not null,
  fecha timestamptz not null default now(),
  unique (usuario_id, nivel, tipo, valor)
);

create or replace function public.xp_requerido_nivel(nivel_actual integer)
returns integer
language sql
immutable
as $$
  select case
    when nivel_actual >= 100 then 0
    else 100 + floor(power(greatest(nivel_actual - 1, 0), 1.45) * 35)::integer + ((nivel_actual - 1) * 15)
  end;
$$;

create or replace function public.calcular_nivel_por_xp(xp_total integer)
returns integer
language plpgsql
immutable
as $$
declare
  nivel_actual integer := 1;
  acumulado integer := 0;
  requisito integer;
begin
  while nivel_actual < 100 loop
    requisito := public.xp_requerido_nivel(nivel_actual);
    exit when greatest(xp_total, 0) < acumulado + requisito;
    acumulado := acumulado + requisito;
    nivel_actual := nivel_actual + 1;
  end loop;

  return nivel_actual;
end;
$$;

create or replace function public.actualizar_nivel_desde_xp()
returns trigger
language plpgsql
as $$
begin
  new.xp := greatest(coalesce(new.xp, 0), 0);
  new.nivel := public.calcular_nivel_por_xp(new.xp);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists progreso_nivel_calcular_nivel on public.progreso_nivel;
create trigger progreso_nivel_calcular_nivel
before insert or update of xp on public.progreso_nivel
for each row
execute function public.actualizar_nivel_desde_xp();

create index if not exists progreso_nivel_ranking_idx
on public.progreso_nivel (nivel desc, xp desc);

create index if not exists historial_xp_usuario_fecha_idx
on public.historial_xp (usuario_id, fecha desc);

create or replace view public.ranking_nivel as
select
  usuario_id,
  temporada_id,
  xp,
  nivel,
  rank() over (partition by temporada_id order by nivel desc, xp desc, updated_at asc) as posicion,
  updated_at
from public.progreso_nivel;

insert into public.recompensas_nivel (nivel, tipo, valor, metadata)
select
  nivel,
  case
    when nivel % 10 = 0 then 'titulo'
    when nivel % 5 = 0 then 'medalla'
    when nivel % 3 = 0 then 'estilo'
    else 'xp_bonus'
  end as tipo,
  case
    when nivel % 10 = 0 then
      (array['Novato', 'Aspirante', 'Competidor', 'Calculador', 'Estratega', 'Especialista', 'Veterano', 'Maestro', 'Campeon', 'Leyenda'])[(ceil(nivel / 10.0))::integer] || ' ' || nivel
    when nivel % 5 = 0 then 'Medalla nivel ' || nivel
    when nivel % 3 = 0 then 'Borde de perfil nivel ' || nivel
    else 'Bonus de temporada nivel ' || nivel
  end as valor,
  jsonb_build_object('season_pass', true)
from generate_series(1, 100) as nivel
on conflict (nivel, tipo, valor) do nothing;
create or replace function public.limpiar_datos_usuario_torneo(usuario_borrado text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  objetivo record;
begin
  if usuario_borrado is null or btrim(usuario_borrado) = '' then
    return;
  end if;

  for objetivo in
    select *
    from (values
      ('ranking', 'usuario'),
      ('ranking', 'usuario_id'),
      ('ranking_ajedrez', 'usuario'),
      ('ranking_ajedrez', 'usuario_id'),
      ('ranking_domino', 'usuario'),
      ('ranking_domino', 'usuario_id'),
      ('ranking_damas', 'usuario'),
      ('ranking_damas', 'usuario_id'),
      ('partidas', 'usuario'),
      ('partidas', 'usuario_id'),
      ('estadisticas_logros', 'usuario'),
      ('progreso_nivel', 'usuario_id'),
      ('historial_xp', 'usuario_id'),
      ('recompensas_desbloqueadas', 'usuario_id')
    ) as pendientes(tabla, columna)
    where to_regclass('public.' || pendientes.tabla) is not null
      and exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = pendientes.tabla
          and column_name = pendientes.columna
      )
  loop
    execute format('delete from public.%I where %I = $1', objetivo.tabla, objetivo.columna)
    using usuario_borrado;
  end loop;
end;
$$;

create or replace function public.limpiar_datos_usuario_torneo_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.limpiar_datos_usuario_torneo(old.usuario);
  return old;
end;
$$;

do $$
begin
  if to_regclass('public.usuarios') is not null
    and exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'usuarios'
        and column_name = 'usuario'
    )
  then
    execute 'drop trigger if exists usuarios_limpiar_datos_torneo on public.usuarios';
    execute '
      create trigger usuarios_limpiar_datos_torneo
      after delete on public.usuarios
      for each row
      execute function public.limpiar_datos_usuario_torneo_trigger()
    ';
  end if;
end;
$$;