-- Sistema VIP base para GameWorld.
-- Ejecutar en Supabase SQL Editor despues de las migraciones principales.

create table if not exists public.vip_memberships (
  id bigint generated by default as identity primary key,
  usuario_id text not null unique,
  is_active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vip_memberships_usuario_id_check check (btrim(usuario_id) <> '')
);

create index if not exists vip_memberships_active_idx
on public.vip_memberships (is_active, expires_at);

create table if not exists public.vip_game_results (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  game_key text not null,
  game_title text not null,
  mode text,
  score integer not null default 0,
  metrics jsonb not null default '{}'::jsonb,
  rewards jsonb not null default '{}'::jsonb,
  origin text not null default 'vip',
  created_at timestamptz not null default now(),
  constraint vip_game_results_usuario_check check (btrim(usuario_id) <> ''),
  constraint vip_game_results_game_key_check check (btrim(game_key) <> ''),
  constraint vip_game_results_score_check check (score >= 0),
  constraint vip_game_results_origin_check check (origin = 'vip')
);

create index if not exists vip_game_results_usuario_idx
on public.vip_game_results (usuario_id, created_at desc);

create index if not exists vip_game_results_game_idx
on public.vip_game_results (game_key, score desc, created_at desc);

create table if not exists public.vip_wallets (
  usuario_id text primary key,
  vip_coins bigint not null default 0 check (vip_coins >= 0),
  vip_xp bigint not null default 0 check (vip_xp >= 0),
  vip_tickets bigint not null default 0 check (vip_tickets >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vip_wallets_usuario_check check (btrim(usuario_id) <> '')
);

create table if not exists public.vip_wallet_transactions (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  tipo text not null check (tipo in ('earn', 'spend', 'convert')),
  vip_coins_delta bigint not null default 0,
  vip_xp_delta bigint not null default 0,
  vip_tickets_delta bigint not null default 0,
  normal_coins_delta bigint not null default 0,
  source text not null default 'vip',
  reference_id text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint vip_wallet_transactions_usuario_check check (btrim(usuario_id) <> '')
);

create index if not exists vip_wallet_transactions_usuario_idx
on public.vip_wallet_transactions (usuario_id, created_at desc);

create table if not exists public.vip_coin_conversions (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  vip_coins_spent bigint not null check (vip_coins_spent > 0),
  normal_coins_received bigint not null check (normal_coins_received > 0),
  conversion_rate integer not null default 100 check (conversion_rate > 0),
  created_at timestamptz not null default now(),
  constraint vip_coin_conversions_usuario_check check (btrim(usuario_id) <> '')
);

create index if not exists vip_coin_conversions_usuario_fecha_idx
on public.vip_coin_conversions (usuario_id, created_at desc);

create table if not exists public.vip_bingo_rooms (
  id text primary key,
  created_by text not null,
  status text not null default 'active' check (status in ('waiting', 'active', 'finished')),
  called_numbers jsonb not null default '[]'::jsonb,
  winner_usuario_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vip_bingo_rooms_id_check check (btrim(id) <> ''),
  constraint vip_bingo_rooms_created_by_check check (btrim(created_by) <> '')
);

create table if not exists public.vip_bingo_players (
  id bigint generated by default as identity primary key,
  room_id text not null references public.vip_bingo_rooms(id) on delete cascade,
  usuario_id text not null,
  card jsonb not null,
  marked_numbers jsonb not null default '[0]'::jsonb,
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (room_id, usuario_id),
  constraint vip_bingo_players_usuario_check check (btrim(usuario_id) <> ''),
  constraint vip_bingo_players_card_check check (jsonb_typeof(card) = 'array'),
  constraint vip_bingo_players_marked_check check (jsonb_typeof(marked_numbers) = 'array')
);

create index if not exists vip_bingo_players_room_idx
on public.vip_bingo_players (room_id, joined_at);

create table if not exists public.vip_roulette_rewards (
  id bigint generated by default as identity primary key,
  reward_key text not null unique,
  label text not null,
  reward_type text not null check (reward_type in ('vip_coins', 'vip_xp', 'vip_tickets', 'cosmetic', 'boost')),
  amount bigint not null default 0 check (amount >= 0),
  weight integer not null default 1 check (weight > 0),
  is_active boolean not null default true,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vip_roulette_rewards_key_check check (btrim(reward_key) <> ''),
  constraint vip_roulette_rewards_label_check check (btrim(label) <> '')
);

create index if not exists vip_roulette_rewards_active_idx
on public.vip_roulette_rewards (is_active, weight);

create table if not exists public.vip_roulette_spins (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  reward_id bigint references public.vip_roulette_rewards(id),
  reward_snapshot jsonb not null default '{}'::jsonb,
  cooldown_until timestamptz not null,
  created_at timestamptz not null default now(),
  constraint vip_roulette_spins_usuario_check check (btrim(usuario_id) <> '')
);

create index if not exists vip_roulette_spins_usuario_fecha_idx
on public.vip_roulette_spins (usuario_id, created_at desc);

create table if not exists public.vip_social_presence (
  usuario_id text primary key,
  display_name text not null,
  last_seen_at timestamptz not null default now(),
  status text not null default 'online' check (status in ('online', 'idle')),
  current_room text not null default 'vip-lounge',
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vip_social_presence_usuario_check check (btrim(usuario_id) <> ''),
  constraint vip_social_presence_display_check check (btrim(display_name) <> '')
);

create index if not exists vip_social_presence_seen_idx
on public.vip_social_presence (last_seen_at desc);

create table if not exists public.vip_events (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  event_type text not null default 'general',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  is_active boolean not null default true,
  related_game text,
  rewards jsonb not null default '{}'::jsonb,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vip_events_name_check check (btrim(name) <> ''),
  constraint vip_events_dates_check check (ends_at > starts_at),
  constraint vip_events_type_check check (btrim(event_type) <> '')
);

create index if not exists vip_events_active_idx
on public.vip_events (is_active, starts_at, ends_at);

create table if not exists public.vip_event_rewards (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.vip_events(id) on delete cascade,
  reward_type text not null,
  amount bigint not null default 0 check (amount >= 0),
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint vip_event_rewards_type_check check (btrim(reward_type) <> '')
);

create index if not exists vip_event_rewards_event_idx
on public.vip_event_rewards (event_id);

insert into public.vip_roulette_rewards (reward_key, label, reward_type, amount, weight, detail)
values
  ('coins-small', '25 monedas VIP', 'vip_coins', 25, 28, '{}'::jsonb),
  ('xp-small', '60 XP VIP', 'vip_xp', 60, 24, '{}'::jsonb),
  ('coins-medium', '60 monedas VIP', 'vip_coins', 60, 18, '{}'::jsonb),
  ('ticket-one', '1 ticket VIP', 'vip_tickets', 1, 12, '{}'::jsonb),
  ('xp-large', '140 XP VIP', 'vip_xp', 140, 10, '{}'::jsonb),
  ('coins-large', '120 monedas VIP', 'vip_coins', 120, 6, '{}'::jsonb),
  ('ticket-two', '2 tickets VIP', 'vip_tickets', 2, 2, '{}'::jsonb)
on conflict (reward_key) do update
set label = excluded.label,
    reward_type = excluded.reward_type,
    amount = excluded.amount,
    weight = excluded.weight,
    detail = excluded.detail,
    updated_at = now();

-- Compatibilidad con la tienda principal. Si ya existe por supabase-experiencia-tienda.sql,
-- esto no cambia su estructura.
create table if not exists public.usuario_monedas (
  usuario_id text primary key,
  saldo bigint not null default 0 check (saldo >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.vip_touch_wallet_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists vip_wallets_touch_updated_at on public.vip_wallets;

create trigger vip_wallets_touch_updated_at
before update on public.vip_wallets
for each row
execute function public.vip_touch_wallet_updated_at();

create or replace function public.vip_bingo_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists vip_bingo_rooms_touch_updated_at on public.vip_bingo_rooms;

create trigger vip_bingo_rooms_touch_updated_at
before update on public.vip_bingo_rooms
for each row
execute function public.vip_bingo_touch_updated_at();

drop trigger if exists vip_bingo_players_touch_updated_at on public.vip_bingo_players;

create trigger vip_bingo_players_touch_updated_at
before update on public.vip_bingo_players
for each row
execute function public.vip_bingo_touch_updated_at();

drop trigger if exists vip_roulette_rewards_touch_updated_at on public.vip_roulette_rewards;

create trigger vip_roulette_rewards_touch_updated_at
before update on public.vip_roulette_rewards
for each row
execute function public.vip_bingo_touch_updated_at();

drop trigger if exists vip_social_presence_touch_updated_at on public.vip_social_presence;

create trigger vip_social_presence_touch_updated_at
before update on public.vip_social_presence
for each row
execute function public.vip_bingo_touch_updated_at();

drop trigger if exists vip_events_touch_updated_at on public.vip_events;

create trigger vip_events_touch_updated_at
before update on public.vip_events
for each row
execute function public.vip_bingo_touch_updated_at();

create or replace function public.vip_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists vip_memberships_touch_updated_at on public.vip_memberships;

create trigger vip_memberships_touch_updated_at
before update on public.vip_memberships
for each row
execute function public.vip_touch_updated_at();

create or replace function public.obtener_estado_vip(p_usuario text, p_codigo text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  codigo_limpio text := btrim(coalesce(p_codigo, ''));
  codigo_usuario text;
  membresia record;
  expirado boolean := false;
begin
  if usuario_limpio = '' then
    return jsonb_build_object('ok', false, 'is_active', false, 'mensaje', 'Inicia sesion para entrar a la Zona VIP.');
  end if;

  if to_regclass('public.usuarios') is null then
    return jsonb_build_object('ok', false, 'is_active', false, 'mensaje', 'No se pudo validar tu usuario.');
  end if;

  execute 'select codigo::text from public.usuarios where usuario = $1 limit 1'
  into codigo_usuario
  using usuario_limpio;

  if codigo_usuario is null then
    return jsonb_build_object('ok', false, 'is_active', false, 'mensaje', 'Inicia sesion para entrar a la Zona VIP.');
  end if;

  if codigo_limpio = '' then
    return jsonb_build_object('ok', false, 'is_active', false, 'mensaje', 'Vuelve a iniciar sesion para validar tu acceso VIP.');
  end if;

  if codigo_usuario <> codigo_limpio then
    return jsonb_build_object('ok', false, 'is_active', false, 'mensaje', 'No se pudo validar tu sesion VIP.');
  end if;

  select *
  into membresia
  from public.vip_memberships
  where usuario_id = usuario_limpio
  limit 1;

  if not found then
    return jsonb_build_object(
      'ok', true,
      'is_active', false,
      'is_vip', false,
      'expires_at', null,
      'mensaje', 'No eres VIP todavia. Puedes comprar el acceso VIP desde la tienda.'
    );
  end if;

  expirado := membresia.expires_at is not null and membresia.expires_at <= now();

  return jsonb_build_object(
    'ok', true,
    'is_active', membresia.is_active and not expirado,
    'is_vip', membresia.is_active and not expirado,
    'expires_at', membresia.expires_at,
    'mensaje', case
      when membresia.is_active and not expirado then 'Acceso VIP activo.'
      when expirado then 'Tu acceso VIP expiro.'
      else 'Tu acceso VIP no esta activo.'
    end
  );
end;
$$;

create or replace function public.registrar_resultado_juego_vip(
  p_usuario text,
  p_codigo text default null,
  p_game_key text default null,
  p_game_title text default null,
  p_mode text default null,
  p_score integer default 0,
  p_metrics jsonb default '{}'::jsonb,
  p_rewards jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  game_key_limpio text := lower(btrim(coalesce(p_game_key, '')));
  game_title_limpio text := btrim(coalesce(p_game_title, p_game_key, 'Juego VIP'));
  clean_score integer := greatest(0, coalesce(p_score, 0));
  clean_metrics jsonb := coalesce(p_metrics, '{}'::jsonb);
  resultado public.vip_game_results%rowtype;
  reward_coins bigint;
  reward_xp bigint;
  reward_tickets bigint;
  reward_payload jsonb;
  wallet public.vip_wallets%rowtype;
  metric_hits bigint := 0;
  metric_accuracy numeric := 0;
  metric_combo bigint := 0;
  bingo_room_id text;
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object(
      'ok', false,
      'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.')
    );
  end if;

  if game_key_limpio = '' then
    return jsonb_build_object('ok', false, 'mensaje', 'Juego VIP invalido.');
  end if;

  if game_key_limpio = 'reflejos-vip' then
    metric_hits := case
      when coalesce(clean_metrics->>'hits', '') ~ '^[0-9]+$' then (clean_metrics->>'hits')::bigint
      else 0
    end;
    metric_accuracy := case
      when coalesce(clean_metrics->>'accuracy', '') ~ '^[0-9]+(\.[0-9]+)?$' then least(100, greatest(0, (clean_metrics->>'accuracy')::numeric))
      else 0
    end;
    metric_combo := case
      when coalesce(clean_metrics->>'bestCombo', clean_metrics->>'combo', '') ~ '^[0-9]+$' then coalesce(clean_metrics->>'bestCombo', clean_metrics->>'combo')::bigint
      else 0
    end;
    reward_coins := least(180, floor(clean_score / 18.0)::bigint + floor(metric_hits / 4.0)::bigint);
    reward_xp := least(320, floor(clean_score / 10.0)::bigint + round(metric_accuracy / 4.0)::bigint);
    reward_tickets := case when clean_score >= 500 or metric_combo >= 20 then 1 else 0 end;
  elsif game_key_limpio = 'bingo-vip' and lower(coalesce(clean_metrics->>'bingo', 'false')) = 'true' then
    bingo_room_id := nullif(btrim(coalesce(clean_metrics->>'roomId', '')), '');

    if bingo_room_id is not null then
      select *
      into resultado
      from public.vip_game_results
      where usuario_id = usuario_limpio
        and game_key = 'bingo-vip'
        and metrics->>'roomId' = bingo_room_id
        and lower(coalesce(metrics->>'bingo', 'false')) = 'true'
      order by created_at asc
      limit 1;

      if found then
        insert into public.vip_wallets (usuario_id)
        values (usuario_limpio)
        on conflict (usuario_id) do nothing;

        select *
        into wallet
        from public.vip_wallets
        where usuario_id = usuario_limpio;

        return jsonb_build_object(
          'ok', true,
          'duplicate', true,
          'mensaje', 'Este Bingo VIP ya tenia recompensa registrada.',
          'wallet', jsonb_build_object(
            'usuario_id', wallet.usuario_id,
            'vipCoins', wallet.vip_coins,
            'vipXp', wallet.vip_xp,
            'vipTickets', wallet.vip_tickets,
            'updated_at', wallet.updated_at
          ),
          'result', jsonb_build_object(
            'id', resultado.id,
            'usuario_id', resultado.usuario_id,
            'game_key', resultado.game_key,
            'game_title', resultado.game_title,
            'mode', resultado.mode,
            'score', resultado.score,
            'metrics', resultado.metrics,
            'rewards', resultado.rewards,
            'origin', resultado.origin,
            'created_at', resultado.created_at
          )
        );
      end if;
    end if;

    reward_coins := 35;
    reward_xp := 80;
    reward_tickets := 1;
  else
    reward_coins := 0;
    reward_xp := 0;
    reward_tickets := 0;
  end if;

  reward_payload := jsonb_build_object(
    'vipCoins', reward_coins,
    'vipXp', reward_xp,
    'vipTickets', reward_tickets
  );

  insert into public.vip_game_results (
    usuario_id,
    game_key,
    game_title,
    mode,
    score,
    metrics,
    rewards,
    origin
  )
  values (
    usuario_limpio,
    game_key_limpio,
    game_title_limpio,
    nullif(btrim(coalesce(p_mode, '')), ''),
    clean_score,
    clean_metrics,
    reward_payload,
    'vip'
  )
  returning *
  into resultado;

  insert into public.vip_wallets (usuario_id, vip_coins, vip_xp, vip_tickets)
  values (usuario_limpio, reward_coins, reward_xp, reward_tickets)
  on conflict (usuario_id) do update
    set vip_coins = public.vip_wallets.vip_coins + excluded.vip_coins,
        vip_xp = public.vip_wallets.vip_xp + excluded.vip_xp,
        vip_tickets = public.vip_wallets.vip_tickets + excluded.vip_tickets,
        updated_at = now()
  returning *
  into wallet;

  if reward_coins > 0 or reward_xp > 0 or reward_tickets > 0 then
    insert into public.vip_wallet_transactions (
      usuario_id,
      tipo,
      vip_coins_delta,
      vip_xp_delta,
      vip_tickets_delta,
      source,
      reference_id,
      detail
    )
    values (
      usuario_limpio,
      'earn',
      reward_coins,
      reward_xp,
      reward_tickets,
      'vip_game',
      resultado.id::text,
      jsonb_build_object('game_key', resultado.game_key, 'mode', resultado.mode, 'score', resultado.score)
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'wallet', jsonb_build_object(
      'usuario_id', wallet.usuario_id,
      'vipCoins', wallet.vip_coins,
      'vipXp', wallet.vip_xp,
      'vipTickets', wallet.vip_tickets,
      'updated_at', wallet.updated_at
    ),
    'result', jsonb_build_object(
      'id', resultado.id,
      'usuario_id', resultado.usuario_id,
      'game_key', resultado.game_key,
      'game_title', resultado.game_title,
      'mode', resultado.mode,
      'score', resultado.score,
      'metrics', resultado.metrics,
      'rewards', resultado.rewards,
      'origin', resultado.origin,
      'created_at', resultado.created_at
    )
  );
end;
$$;

create or replace function public.obtener_billetera_vip(
  p_usuario text,
  p_codigo text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  wallet public.vip_wallets%rowtype;
  convertido_hoy bigint;
  limite_diario bigint := 50;
  tasa integer := 100;
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object(
      'ok', false,
      'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.')
    );
  end if;

  insert into public.vip_wallets (usuario_id)
  values (usuario_limpio)
  on conflict (usuario_id) do nothing;

  select *
  into wallet
  from public.vip_wallets
  where usuario_id = usuario_limpio;

  select coalesce(sum(vip_coins_spent), 0)
  into convertido_hoy
  from public.vip_coin_conversions
  where usuario_id = usuario_limpio
    and created_at >= date_trunc('day', now());

  return jsonb_build_object(
    'ok', true,
    'wallet', jsonb_build_object(
      'usuario_id', wallet.usuario_id,
      'vipCoins', wallet.vip_coins,
      'vipXp', wallet.vip_xp,
      'vipTickets', wallet.vip_tickets,
      'updated_at', wallet.updated_at
    ),
    'conversion', jsonb_build_object(
      'rate', tasa,
      'dailyLimitVipCoins', limite_diario,
      'convertedTodayVipCoins', convertido_hoy,
      'remainingTodayVipCoins', greatest(0, limite_diario - convertido_hoy)
    )
  );
end;
$$;

create or replace function public.convertir_monedas_vip(
  p_usuario text,
  p_codigo text default null,
  p_vip_coins bigint default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  cantidad bigint := greatest(0, coalesce(p_vip_coins, 0));
  tasa integer := 100;
  limite_diario bigint := 50;
  convertido_hoy bigint;
  disponible_hoy bigint;
  monedas_normales bigint;
  wallet public.vip_wallets%rowtype;
  saldo_normal bigint;
  conversion_id bigint;
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object(
      'ok', false,
      'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.')
    );
  end if;

  if cantidad <= 0 then
    return jsonb_build_object('ok', false, 'mensaje', 'Ingresa una cantidad valida de monedas VIP.');
  end if;

  if cantidad > limite_diario then
    return jsonb_build_object('ok', false, 'mensaje', 'La conversion supera el limite diario VIP.');
  end if;

  insert into public.vip_wallets (usuario_id)
  values (usuario_limpio)
  on conflict (usuario_id) do nothing;

  select *
  into wallet
  from public.vip_wallets
  where usuario_id = usuario_limpio
  for update;

  if wallet.vip_coins < cantidad then
    return jsonb_build_object('ok', false, 'mensaje', 'No tienes suficientes monedas VIP.');
  end if;

  select coalesce(sum(vip_coins_spent), 0)
  into convertido_hoy
  from public.vip_coin_conversions
  where usuario_id = usuario_limpio
    and created_at >= date_trunc('day', now());

  disponible_hoy := greatest(0, limite_diario - convertido_hoy);

  if cantidad > disponible_hoy then
    return jsonb_build_object(
      'ok', false,
      'mensaje', 'Ya alcanzaste el limite diario de conversion VIP.',
      'remainingTodayVipCoins', disponible_hoy
    );
  end if;

  monedas_normales := cantidad * tasa;

  update public.vip_wallets
  set vip_coins = vip_coins - cantidad,
      updated_at = now()
  where usuario_id = usuario_limpio
  returning *
  into wallet;

  insert into public.usuario_monedas (usuario_id, saldo)
  values (usuario_limpio, monedas_normales)
  on conflict (usuario_id) do update
    set saldo = public.usuario_monedas.saldo + excluded.saldo,
        updated_at = now()
  returning saldo
  into saldo_normal;

  insert into public.vip_coin_conversions (
    usuario_id,
    vip_coins_spent,
    normal_coins_received,
    conversion_rate
  )
  values (
    usuario_limpio,
    cantidad,
    monedas_normales,
    tasa
  )
  returning id
  into conversion_id;

  insert into public.vip_wallet_transactions (
    usuario_id,
    tipo,
    vip_coins_delta,
    normal_coins_delta,
    source,
    reference_id,
    detail
  )
  values (
    usuario_limpio,
    'convert',
    -cantidad,
    monedas_normales,
    'vip_conversion',
    conversion_id::text,
    jsonb_build_object('rate', tasa, 'dailyLimitVipCoins', limite_diario)
  );

  return jsonb_build_object(
    'ok', true,
    'mensaje', 'Conversion VIP completada.',
    'wallet', jsonb_build_object(
      'usuario_id', wallet.usuario_id,
      'vipCoins', wallet.vip_coins,
      'vipXp', wallet.vip_xp,
      'vipTickets', wallet.vip_tickets,
      'updated_at', wallet.updated_at
    ),
    'conversion', jsonb_build_object(
      'id', conversion_id,
      'vipCoinsSpent', cantidad,
      'normalCoinsReceived', monedas_normales,
      'rate', tasa,
      'dailyLimitVipCoins', limite_diario,
      'convertedTodayVipCoins', convertido_hoy + cantidad,
      'remainingTodayVipCoins', greatest(0, limite_diario - convertido_hoy - cantidad)
    ),
    'normalCoinsBalance', saldo_normal
  );
end;
$$;

create or replace function public.vip_bingo_generar_carton()
returns jsonb
language plpgsql
as $$
declare
  b integer[];
  i integer[];
  n integer[];
  g integer[];
  o integer[];
  card integer[] := '{}';
  fila integer;
begin
  select array_agg(valor) into b from (select valor from generate_series(1, 15) valor order by random() limit 5) s;
  select array_agg(valor) into i from (select valor from generate_series(16, 30) valor order by random() limit 5) s;
  select array_agg(valor) into n from (select valor from generate_series(31, 45) valor order by random() limit 5) s;
  select array_agg(valor) into g from (select valor from generate_series(46, 60) valor order by random() limit 5) s;
  select array_agg(valor) into o from (select valor from generate_series(61, 75) valor order by random() limit 5) s;

  for fila in 1..5 loop
    card := card || b[fila] || i[fila] || case when fila = 3 then 0 else n[fila] end || g[fila] || o[fila];
  end loop;

  return to_jsonb(card);
end;
$$;

create or replace function public.vip_bingo_numero_marcado(p_card jsonb, p_marked jsonb, p_index integer)
returns boolean
language plpgsql
stable
as $$
declare
  valor integer;
begin
  valor := coalesce((p_card->>p_index)::integer, -1);
  if valor = 0 then
    return true;
  end if;

  return exists (
    select 1
    from jsonb_array_elements_text(coalesce(p_marked, '[]'::jsonb)) item(value)
    where item.value = valor::text
  );
end;
$$;

create or replace function public.vip_bingo_tiene_linea(p_card jsonb, p_marked jsonb)
returns boolean
language plpgsql
stable
as $$
declare
  fila integer;
  columna integer;
begin
  if jsonb_array_length(coalesce(p_card, '[]'::jsonb)) <> 25 then
    return false;
  end if;

  for fila in 0..4 loop
    if public.vip_bingo_numero_marcado(p_card, p_marked, fila * 5)
      and public.vip_bingo_numero_marcado(p_card, p_marked, fila * 5 + 1)
      and public.vip_bingo_numero_marcado(p_card, p_marked, fila * 5 + 2)
      and public.vip_bingo_numero_marcado(p_card, p_marked, fila * 5 + 3)
      and public.vip_bingo_numero_marcado(p_card, p_marked, fila * 5 + 4) then
      return true;
    end if;
  end loop;

  for columna in 0..4 loop
    if public.vip_bingo_numero_marcado(p_card, p_marked, columna)
      and public.vip_bingo_numero_marcado(p_card, p_marked, columna + 5)
      and public.vip_bingo_numero_marcado(p_card, p_marked, columna + 10)
      and public.vip_bingo_numero_marcado(p_card, p_marked, columna + 15)
      and public.vip_bingo_numero_marcado(p_card, p_marked, columna + 20) then
      return true;
    end if;
  end loop;

  if public.vip_bingo_numero_marcado(p_card, p_marked, 0)
    and public.vip_bingo_numero_marcado(p_card, p_marked, 6)
    and public.vip_bingo_numero_marcado(p_card, p_marked, 12)
    and public.vip_bingo_numero_marcado(p_card, p_marked, 18)
    and public.vip_bingo_numero_marcado(p_card, p_marked, 24) then
    return true;
  end if;

  if public.vip_bingo_numero_marcado(p_card, p_marked, 4)
    and public.vip_bingo_numero_marcado(p_card, p_marked, 8)
    and public.vip_bingo_numero_marcado(p_card, p_marked, 12)
    and public.vip_bingo_numero_marcado(p_card, p_marked, 16)
    and public.vip_bingo_numero_marcado(p_card, p_marked, 20) then
    return true;
  end if;

  return false;
end;
$$;

create or replace function public.vip_bingo_payload(p_room_id text, p_usuario text)
returns jsonb
language plpgsql
stable
as $$
declare
  sala record;
  jugador record;
  jugador_encontrado boolean := false;
  jugadores jsonb;
begin
  select *
  into sala
  from public.vip_bingo_rooms
  where id = p_room_id;

  if not found then
    return jsonb_build_object('ok', false, 'mensaje', 'Sala VIP no encontrada.');
  end if;

  select *
  into jugador
  from public.vip_bingo_players
  where room_id = p_room_id
    and usuario_id = p_usuario;
  jugador_encontrado := found;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'usuario_id', usuario_id,
      'joined_at', joined_at
    )
    order by joined_at
  ), '[]'::jsonb)
  into jugadores
  from public.vip_bingo_players
  where room_id = p_room_id;

  return jsonb_build_object(
    'ok', true,
    'room', jsonb_build_object(
      'id', sala.id,
      'created_by', sala.created_by,
      'status', sala.status,
      'called_numbers', sala.called_numbers,
      'winner_usuario_id', sala.winner_usuario_id,
      'created_at', sala.created_at,
      'updated_at', sala.updated_at
    ),
    'player', case when not jugador_encontrado then null else jsonb_build_object(
      'usuario_id', jugador.usuario_id,
      'card', jugador.card,
      'marked_numbers', jugador.marked_numbers,
      'joined_at', jugador.joined_at,
      'updated_at', jugador.updated_at
    ) end,
    'players', jugadores
  );
end;
$$;

create or replace function public.vip_bingo_crear_sala(
  p_usuario text,
  p_codigo text default null,
  p_room_id text default 'vip-main'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  sala_limpia text := lower(regexp_replace(btrim(coalesce(p_room_id, 'vip-main')), '[^a-zA-Z0-9_-]', '', 'g'));
  sala_estaba_finalizada boolean := false;
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object('ok', false, 'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.'));
  end if;

  sala_limpia := coalesce(nullif(left(sala_limpia, 32), ''), 'vip-main');

  select exists (
    select 1
    from public.vip_bingo_rooms
    where id = sala_limpia
      and status = 'finished'
  )
  into sala_estaba_finalizada;

  insert into public.vip_bingo_rooms (id, created_by, status)
  values (sala_limpia, usuario_limpio, 'active')
  on conflict (id) do update
    set status = 'active',
        called_numbers = case when public.vip_bingo_rooms.status = 'finished' then '[]'::jsonb else public.vip_bingo_rooms.called_numbers end,
        winner_usuario_id = case when public.vip_bingo_rooms.status = 'finished' then null else public.vip_bingo_rooms.winner_usuario_id end,
        updated_at = now();

  if sala_estaba_finalizada then
    delete from public.vip_bingo_players
    where room_id = sala_limpia;
  end if;

  insert into public.vip_bingo_players (room_id, usuario_id, card, marked_numbers)
  values (sala_limpia, usuario_limpio, public.vip_bingo_generar_carton(), '[0]'::jsonb)
  on conflict (room_id, usuario_id) do nothing;

  return public.vip_bingo_payload(sala_limpia, usuario_limpio);
end;
$$;

create or replace function public.vip_bingo_unirse_sala(
  p_usuario text,
  p_codigo text default null,
  p_room_id text default 'vip-main'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  sala_limpia text := lower(regexp_replace(btrim(coalesce(p_room_id, 'vip-main')), '[^a-zA-Z0-9_-]', '', 'g'));
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object('ok', false, 'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.'));
  end if;

  sala_limpia := coalesce(nullif(left(sala_limpia, 32), ''), 'vip-main');

  insert into public.vip_bingo_rooms (id, created_by, status)
  values (sala_limpia, usuario_limpio, 'active')
  on conflict (id) do nothing;

  insert into public.vip_bingo_players (room_id, usuario_id, card, marked_numbers)
  values (sala_limpia, usuario_limpio, public.vip_bingo_generar_carton(), '[0]'::jsonb)
  on conflict (room_id, usuario_id) do nothing;

  return public.vip_bingo_payload(sala_limpia, usuario_limpio);
end;
$$;

create or replace function public.vip_bingo_obtener_sala(
  p_usuario text,
  p_codigo text default null,
  p_room_id text default 'vip-main'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  sala_limpia text := lower(regexp_replace(btrim(coalesce(p_room_id, 'vip-main')), '[^a-zA-Z0-9_-]', '', 'g'));
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object('ok', false, 'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.'));
  end if;

  sala_limpia := coalesce(nullif(left(sala_limpia, 32), ''), 'vip-main');

  if not exists (select 1 from public.vip_bingo_players where room_id = sala_limpia and usuario_id = usuario_limpio) then
    return public.vip_bingo_unirse_sala(usuario_limpio, p_codigo, sala_limpia);
  end if;

  return public.vip_bingo_payload(sala_limpia, usuario_limpio);
end;
$$;

create or replace function public.vip_bingo_cantar_numero(
  p_usuario text,
  p_codigo text default null,
  p_room_id text default 'vip-main'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  sala_limpia text := lower(regexp_replace(btrim(coalesce(p_room_id, 'vip-main')), '[^a-zA-Z0-9_-]', '', 'g'));
  llamados jsonb;
  numero integer;
  intentos integer := 0;
  payload jsonb;
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object('ok', false, 'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.'));
  end if;

  sala_limpia := coalesce(nullif(left(sala_limpia, 32), ''), 'vip-main');

  perform 1 from public.vip_bingo_rooms where id = sala_limpia for update;
  if not found then
    return public.vip_bingo_unirse_sala(usuario_limpio, p_codigo, sala_limpia);
  end if;

  select called_numbers
  into llamados
  from public.vip_bingo_rooms
  where id = sala_limpia;

  if jsonb_array_length(coalesce(llamados, '[]'::jsonb)) >= 75 then
    update public.vip_bingo_rooms
    set status = 'finished'
    where id = sala_limpia;
    return public.vip_bingo_payload(sala_limpia, usuario_limpio) || jsonb_build_object('number', null);
  end if;

  loop
    numero := floor(random() * 75 + 1)::integer;
    exit when not exists (
      select 1 from jsonb_array_elements_text(coalesce(llamados, '[]'::jsonb)) item(value)
      where item.value = numero::text
    );
    intentos := intentos + 1;
    if intentos > 200 then
      select valor
      into numero
      from generate_series(1, 75) valor
      where not exists (
        select 1 from jsonb_array_elements_text(coalesce(llamados, '[]'::jsonb)) item(value)
        where item.value = valor::text
      )
      order by valor
      limit 1;
      exit;
    end if;
  end loop;

  update public.vip_bingo_rooms
  set called_numbers = coalesce(called_numbers, '[]'::jsonb) || to_jsonb(numero),
      status = 'active',
      updated_at = now()
  where id = sala_limpia;

  payload := public.vip_bingo_payload(sala_limpia, usuario_limpio);
  return payload || jsonb_build_object('number', numero);
end;
$$;

create or replace function public.vip_bingo_marcar_numero(
  p_usuario text,
  p_codigo text default null,
  p_room_id text default 'vip-main',
  p_number integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  sala_limpia text := lower(regexp_replace(btrim(coalesce(p_room_id, 'vip-main')), '[^a-zA-Z0-9_-]', '', 'g'));
  jugador record;
  llamados jsonb;
  numero integer := coalesce(p_number, -1);
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object('ok', false, 'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.'));
  end if;

  sala_limpia := coalesce(nullif(left(sala_limpia, 32), ''), 'vip-main');

  select *
  into jugador
  from public.vip_bingo_players
  where room_id = sala_limpia
    and usuario_id = usuario_limpio
  for update;

  if not found then
    return public.vip_bingo_unirse_sala(usuario_limpio, p_codigo, sala_limpia);
  end if;

  if numero < 0 or numero > 75 then
    return jsonb_build_object('ok', false, 'mensaje', 'Numero invalido.');
  end if;

  select called_numbers
  into llamados
  from public.vip_bingo_rooms
  where id = sala_limpia;

  if numero <> 0 and not exists (
    select 1 from jsonb_array_elements_text(coalesce(llamados, '[]'::jsonb)) item(value)
    where item.value = numero::text
  ) then
    return jsonb_build_object('ok', false, 'mensaje', 'Ese numero todavia no ha sido cantado.');
  end if;

  if numero <> 0 and not exists (
    select 1 from jsonb_array_elements_text(jugador.card) item(value)
    where item.value = numero::text
  ) then
    return jsonb_build_object('ok', false, 'mensaje', 'Ese numero no esta en tu carton.');
  end if;

  if not exists (
    select 1 from jsonb_array_elements_text(coalesce(jugador.marked_numbers, '[]'::jsonb)) item(value)
    where item.value = numero::text
  ) then
    update public.vip_bingo_players
    set marked_numbers = coalesce(marked_numbers, '[]'::jsonb) || to_jsonb(numero),
        updated_at = now()
    where id = jugador.id;
  end if;

  return public.vip_bingo_payload(sala_limpia, usuario_limpio);
end;
$$;

create or replace function public.vip_bingo_reclamar(
  p_usuario text,
  p_codigo text default null,
  p_room_id text default 'vip-main'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  sala_limpia text := lower(regexp_replace(btrim(coalesce(p_room_id, 'vip-main')), '[^a-zA-Z0-9_-]', '', 'g'));
  jugador record;
  ganador_actual text;
  tiene_bingo boolean;
  payload jsonb;
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object('ok', false, 'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.'));
  end if;

  sala_limpia := coalesce(nullif(left(sala_limpia, 32), ''), 'vip-main');

  perform 1 from public.vip_bingo_rooms where id = sala_limpia for update;
  if not found then
    return jsonb_build_object('ok', false, 'mensaje', 'Sala VIP no encontrada.');
  end if;

  select *
  into jugador
  from public.vip_bingo_players
  where room_id = sala_limpia
    and usuario_id = usuario_limpio;

  if not found then
    return jsonb_build_object('ok', false, 'mensaje', 'No tienes carton en esta sala.');
  end if;

  select winner_usuario_id
  into ganador_actual
  from public.vip_bingo_rooms
  where id = sala_limpia;

  if ganador_actual is not null then
    payload := public.vip_bingo_payload(sala_limpia, usuario_limpio);
    return payload || jsonb_build_object('winner', ganador_actual = usuario_limpio, 'alreadyFinished', true);
  end if;

  tiene_bingo := public.vip_bingo_tiene_linea(jugador.card, jugador.marked_numbers);

  if tiene_bingo then
    update public.vip_bingo_rooms
    set status = 'finished',
        winner_usuario_id = usuario_limpio,
        updated_at = now()
    where id = sala_limpia;
  end if;

  payload := public.vip_bingo_payload(sala_limpia, usuario_limpio);
  return payload || jsonb_build_object('winner', tiene_bingo);
end;
$$;

create or replace function public.obtener_historial_juegos_vip(
  p_usuario text,
  p_codigo text default null,
  p_game_key text default null,
  p_limit integer default 8
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  game_key_limpio text := nullif(lower(btrim(coalesce(p_game_key, ''))), '');
  limite integer := least(30, greatest(1, coalesce(p_limit, 8)));
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object(
      'ok', false,
      'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.'),
      'items', '[]'::jsonb
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'items',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', id,
          'usuario_id', usuario_id,
          'game_key', game_key,
          'game_title', game_title,
          'mode', mode,
          'score', score,
          'metrics', metrics,
          'rewards', rewards,
          'origin', origin,
          'created_at', created_at
        )
        order by created_at desc
      )
      from (
        select *
        from public.vip_game_results
        where usuario_id = usuario_limpio
          and (game_key_limpio is null or game_key = game_key_limpio)
        order by created_at desc
        limit limite
      ) recientes
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.vip_roulette_obtener_estado(
  p_usuario text,
  p_codigo text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  ultimo record;
  ultimo_encontrado boolean := false;
  cooldown_horas integer := 24;
  disponible_en timestamptz;
  premios jsonb;
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object(
      'ok', false,
      'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.')
    );
  end if;

  select *
  into ultimo
  from public.vip_roulette_spins
  where usuario_id = usuario_limpio
  order by created_at desc
  limit 1;
  ultimo_encontrado := found;

  disponible_en := case
    when ultimo_encontrado and ultimo.cooldown_until > now() then ultimo.cooldown_until
    else null
  end;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'key', reward_key,
      'label', label,
      'type', reward_type,
      'amount', amount,
      'weight', weight
    )
    order by id
  ), '[]'::jsonb)
  into premios
  from public.vip_roulette_rewards
  where is_active = true;

  return jsonb_build_object(
    'ok', true,
    'canSpin', disponible_en is null,
    'cooldownUntil', disponible_en,
    'cooldownHours', cooldown_horas,
    'lastSpin', case when not ultimo_encontrado then null else jsonb_build_object(
      'id', ultimo.id,
      'reward', ultimo.reward_snapshot,
      'created_at', ultimo.created_at,
      'cooldown_until', ultimo.cooldown_until
    ) end,
    'rewards', premios
  );
end;
$$;

create or replace function public.vip_roulette_girar(
  p_usuario text,
  p_codigo text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  ultimo record;
  premio record;
  total_peso integer;
  punto integer;
  acumulado integer := 0;
  cooldown_horas integer := 24;
  cooldown_fin timestamptz := now() + make_interval(hours => 24);
  reward_coins bigint := 0;
  reward_xp bigint := 0;
  reward_tickets bigint := 0;
  spin_id bigint;
  snapshot jsonb;
  wallet public.vip_wallets%rowtype;
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object(
      'ok', false,
      'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.')
    );
  end if;

  select *
  into ultimo
  from public.vip_roulette_spins
  where usuario_id = usuario_limpio
  order by created_at desc
  limit 1;

  if found and ultimo.cooldown_until > now() then
    return jsonb_build_object(
      'ok', false,
      'mensaje', 'Ya usaste tu tirada VIP de hoy.',
      'cooldownUntil', ultimo.cooldown_until
    );
  end if;

  select coalesce(sum(weight), 0)
  into total_peso
  from public.vip_roulette_rewards
  where is_active = true;

  if total_peso <= 0 then
    return jsonb_build_object('ok', false, 'mensaje', 'No hay premios VIP activos.');
  end if;

  punto := floor(random() * total_peso + 1)::integer;

  for premio in
    select *
    from public.vip_roulette_rewards
    where is_active = true
    order by id
  loop
    acumulado := acumulado + premio.weight;
    if acumulado >= punto then
      exit;
    end if;
  end loop;

  if premio.id is null then
    return jsonb_build_object('ok', false, 'mensaje', 'No se pudo seleccionar premio VIP.');
  end if;

  if premio.reward_type = 'vip_coins' then
    reward_coins := premio.amount;
  elsif premio.reward_type = 'vip_xp' then
    reward_xp := premio.amount;
  elsif premio.reward_type = 'vip_tickets' then
    reward_tickets := premio.amount;
  end if;

  snapshot := jsonb_build_object(
    'key', premio.reward_key,
    'label', premio.label,
    'type', premio.reward_type,
    'amount', premio.amount
  );

  insert into public.vip_roulette_spins (usuario_id, reward_id, reward_snapshot, cooldown_until)
  values (usuario_limpio, premio.id, snapshot, cooldown_fin)
  returning id
  into spin_id;

  insert into public.vip_wallets (usuario_id, vip_coins, vip_xp, vip_tickets)
  values (usuario_limpio, reward_coins, reward_xp, reward_tickets)
  on conflict (usuario_id) do update
    set vip_coins = public.vip_wallets.vip_coins + excluded.vip_coins,
        vip_xp = public.vip_wallets.vip_xp + excluded.vip_xp,
        vip_tickets = public.vip_wallets.vip_tickets + excluded.vip_tickets,
        updated_at = now()
  returning *
  into wallet;

  if reward_coins > 0 or reward_xp > 0 or reward_tickets > 0 then
    insert into public.vip_wallet_transactions (
      usuario_id,
      tipo,
      vip_coins_delta,
      vip_xp_delta,
      vip_tickets_delta,
      source,
      reference_id,
      detail
    )
    values (
      usuario_limpio,
      'earn',
      reward_coins,
      reward_xp,
      reward_tickets,
      'vip_roulette',
      spin_id::text,
      snapshot
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'mensaje', 'Tirada VIP completada.',
    'spinId', spin_id,
    'reward', snapshot,
    'cooldownUntil', cooldown_fin,
    'cooldownHours', cooldown_horas,
    'wallet', jsonb_build_object(
      'usuario_id', wallet.usuario_id,
      'vipCoins', wallet.vip_coins,
      'vipXp', wallet.vip_xp,
      'vipTickets', wallet.vip_tickets,
      'updated_at', wallet.updated_at
    )
  );
end;
$$;

create or replace function public.vip_social_ping(
  p_usuario text,
  p_codigo text default null,
  p_room text default 'vip-lounge'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  sala_limpia text := lower(regexp_replace(btrim(coalesce(p_room, 'vip-lounge')), '[^a-zA-Z0-9_-]', '', 'g'));
  usuarios jsonb;
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object(
      'ok', false,
      'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.'),
      'users', '[]'::jsonb
    );
  end if;

  sala_limpia := coalesce(nullif(left(sala_limpia, 32), ''), 'vip-lounge');

  insert into public.vip_social_presence (usuario_id, display_name, last_seen_at, status, current_room)
  values (usuario_limpio, usuario_limpio, now(), 'online', sala_limpia)
  on conflict (usuario_id) do update
    set display_name = excluded.display_name,
        last_seen_at = now(),
        status = 'online',
        current_room = excluded.current_room,
        updated_at = now();

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'usuario_id', usuario_id,
      'display_name', display_name,
      'status', status,
      'current_room', current_room,
      'last_seen_at', last_seen_at
    )
    order by last_seen_at desc
  ), '[]'::jsonb)
  into usuarios
  from public.vip_social_presence
  where current_room = sala_limpia
    and last_seen_at >= now() - interval '5 minutes';

  return jsonb_build_object(
    'ok', true,
    'room', sala_limpia,
    'users', usuarios,
    'activeCount', jsonb_array_length(usuarios)
  );
end;
$$;

create or replace function public.obtener_eventos_vip_activos(
  p_usuario text,
  p_codigo text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object(
      'ok', false,
      'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.'),
      'items', '[]'::jsonb
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'items',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', id,
          'name', name,
          'description', description,
          'event_type', event_type,
          'starts_at', starts_at,
          'ends_at', ends_at,
          'related_game', related_game,
          'rewards', rewards,
          'config', config
        )
        order by ends_at asc, starts_at asc
      )
      from public.vip_events
      where is_active = true
        and starts_at <= now()
        and ends_at > now()
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_guardar_evento_vip(
  p_clave text,
  p_event_id bigint default null,
  p_name text default '',
  p_description text default '',
  p_event_type text default 'general',
  p_starts_at timestamptz default null,
  p_ends_at timestamptz default null,
  p_is_active boolean default true,
  p_related_game text default null,
  p_rewards jsonb default '{}'::jsonb,
  p_config jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  nombre_limpio text := btrim(coalesce(p_name, ''));
  tipo_limpio text := lower(regexp_replace(btrim(coalesce(p_event_type, 'general')), '[^a-zA-Z0-9_-]', '', 'g'));
  juego_limpio text := nullif(lower(regexp_replace(btrim(coalesce(p_related_game, '')), '[^a-zA-Z0-9_-]', '', 'g')), '');
  evento public.vip_events%rowtype;
begin
  if not public.validar_admin_torneo(p_clave) then
    return jsonb_build_object('ok', false, 'mensaje', 'Clave admin invalida');
  end if;

  tipo_limpio := coalesce(nullif(left(tipo_limpio, 32), ''), 'general');

  if nombre_limpio = '' then
    return jsonb_build_object('ok', false, 'mensaje', 'El evento VIP necesita nombre.');
  end if;

  if p_starts_at is null or p_ends_at is null or p_ends_at <= p_starts_at then
    return jsonb_build_object('ok', false, 'mensaje', 'Fechas invalidas para evento VIP.');
  end if;

  if p_event_id is null then
    insert into public.vip_events (
      name,
      description,
      event_type,
      starts_at,
      ends_at,
      is_active,
      related_game,
      rewards,
      config
    )
    values (
      nombre_limpio,
      btrim(coalesce(p_description, '')),
      tipo_limpio,
      p_starts_at,
      p_ends_at,
      coalesce(p_is_active, true),
      juego_limpio,
      coalesce(p_rewards, '{}'::jsonb),
      coalesce(p_config, '{}'::jsonb)
    )
    returning *
    into evento;
  else
    update public.vip_events
    set name = nombre_limpio,
        description = btrim(coalesce(p_description, '')),
        event_type = tipo_limpio,
        starts_at = p_starts_at,
        ends_at = p_ends_at,
        is_active = coalesce(p_is_active, true),
        related_game = juego_limpio,
        rewards = coalesce(p_rewards, '{}'::jsonb),
        config = coalesce(p_config, '{}'::jsonb),
        updated_at = now()
    where id = p_event_id
    returning *
    into evento;

    if not found then
      return jsonb_build_object('ok', false, 'mensaje', 'Evento VIP no encontrado.');
    end if;
  end if;

  return jsonb_build_object(
    'ok', true,
    'mensaje', 'Evento VIP guardado.',
    'event', jsonb_build_object(
      'id', evento.id,
      'name', evento.name,
      'description', evento.description,
      'event_type', evento.event_type,
      'starts_at', evento.starts_at,
      'ends_at', evento.ends_at,
      'is_active', evento.is_active,
      'related_game', evento.related_game,
      'rewards', evento.rewards,
      'config', evento.config,
      'created_at', evento.created_at,
      'updated_at', evento.updated_at
    )
  );
end;
$$;

create or replace function public.admin_listar_eventos_vip(p_clave text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validar_admin_torneo(p_clave) then
    return jsonb_build_object('ok', false, 'mensaje', 'Clave admin invalida', 'items', '[]'::jsonb);
  end if;

  return jsonb_build_object(
    'ok', true,
    'items',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', id,
          'name', name,
          'description', description,
          'event_type', event_type,
          'starts_at', starts_at,
          'ends_at', ends_at,
          'is_active', is_active,
          'is_current', is_active and starts_at <= now() and ends_at > now(),
          'related_game', related_game,
          'rewards', rewards,
          'config', config,
          'created_at', created_at,
          'updated_at', updated_at
        )
        order by starts_at desc, updated_at desc
      )
      from public.vip_events
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_cambiar_estado_evento_vip(
  p_clave text,
  p_event_id bigint,
  p_is_active boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validar_admin_torneo(p_clave) then
    return jsonb_build_object('ok', false, 'mensaje', 'Clave admin invalida');
  end if;

  update public.vip_events
  set is_active = coalesce(p_is_active, false),
      updated_at = now()
  where id = p_event_id;

  if not found then
    return jsonb_build_object('ok', false, 'mensaje', 'Evento VIP no encontrado.');
  end if;

  return jsonb_build_object('ok', true, 'mensaje', 'Estado de evento VIP actualizado.');
end;
$$;

create or replace function public.admin_eliminar_evento_vip(
  p_clave text,
  p_event_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validar_admin_torneo(p_clave) then
    return jsonb_build_object('ok', false, 'mensaje', 'Clave admin invalida');
  end if;

  delete from public.vip_events
  where id = p_event_id;

  if not found then
    return jsonb_build_object('ok', false, 'mensaje', 'Evento VIP no encontrado.');
  end if;

  return jsonb_build_object('ok', true, 'mensaje', 'Evento VIP eliminado.');
end;
$$;

create or replace function public.admin_guardar_membresia_vip(
  p_clave text,
  p_usuario text,
  p_activo boolean default true,
  p_expires_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
begin
  if not public.validar_admin_torneo(p_clave) then
    return jsonb_build_object('ok', false, 'mensaje', 'Clave admin invalida');
  end if;

  if usuario_limpio = '' or to_regclass('public.usuarios') is null then
    return jsonb_build_object('ok', false, 'mensaje', 'Usuario invalido');
  end if;

  if not exists (select 1 from public.usuarios where usuario = usuario_limpio) then
    return jsonb_build_object('ok', false, 'mensaje', 'El usuario no existe');
  end if;

  insert into public.vip_memberships (usuario_id, is_active, expires_at)
  values (usuario_limpio, coalesce(p_activo, true), p_expires_at)
  on conflict (usuario_id) do update
  set is_active = excluded.is_active,
      expires_at = excluded.expires_at,
      updated_at = now();

  return jsonb_build_object('ok', true, 'mensaje', 'Membresia VIP guardada');
end;
$$;

create or replace function public.admin_listar_membresias_vip(p_clave text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validar_admin_torneo(p_clave) then
    return jsonb_build_object('ok', false, 'mensaje', 'Clave admin invalida', 'items', '[]'::jsonb);
  end if;

  return jsonb_build_object(
    'ok', true,
    'items',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'usuario_id', usuario_id,
          'is_active', is_active,
          'expires_at', expires_at,
          'created_at', created_at,
          'updated_at', updated_at,
          'is_valid', is_active and (expires_at is null or expires_at > now())
        )
        order by updated_at desc
      )
      from public.vip_memberships
    ), '[]'::jsonb)
  );
end;
$$;

alter table public.vip_memberships enable row level security;
alter table public.vip_game_results enable row level security;
alter table public.vip_wallets enable row level security;
alter table public.vip_wallet_transactions enable row level security;
alter table public.vip_coin_conversions enable row level security;
alter table public.vip_bingo_rooms enable row level security;
alter table public.vip_bingo_players enable row level security;
alter table public.vip_roulette_rewards enable row level security;
alter table public.vip_roulette_spins enable row level security;
alter table public.vip_social_presence enable row level security;
alter table public.vip_events enable row level security;
alter table public.vip_event_rewards enable row level security;

drop policy if exists vip_memberships_no_direct_select on public.vip_memberships;
drop policy if exists vip_memberships_no_direct_insert on public.vip_memberships;
drop policy if exists vip_memberships_no_direct_update on public.vip_memberships;
drop policy if exists vip_memberships_no_direct_delete on public.vip_memberships;
drop policy if exists vip_game_results_no_direct_select on public.vip_game_results;
drop policy if exists vip_game_results_no_direct_insert on public.vip_game_results;
drop policy if exists vip_game_results_no_direct_update on public.vip_game_results;
drop policy if exists vip_game_results_no_direct_delete on public.vip_game_results;
drop policy if exists vip_wallets_no_direct_select on public.vip_wallets;
drop policy if exists vip_wallets_no_direct_insert on public.vip_wallets;
drop policy if exists vip_wallets_no_direct_update on public.vip_wallets;
drop policy if exists vip_wallets_no_direct_delete on public.vip_wallets;
drop policy if exists vip_wallet_transactions_no_direct_select on public.vip_wallet_transactions;
drop policy if exists vip_wallet_transactions_no_direct_insert on public.vip_wallet_transactions;
drop policy if exists vip_wallet_transactions_no_direct_update on public.vip_wallet_transactions;
drop policy if exists vip_wallet_transactions_no_direct_delete on public.vip_wallet_transactions;
drop policy if exists vip_coin_conversions_no_direct_select on public.vip_coin_conversions;
drop policy if exists vip_coin_conversions_no_direct_insert on public.vip_coin_conversions;
drop policy if exists vip_coin_conversions_no_direct_update on public.vip_coin_conversions;
drop policy if exists vip_coin_conversions_no_direct_delete on public.vip_coin_conversions;
drop policy if exists vip_bingo_rooms_no_direct_select on public.vip_bingo_rooms;
drop policy if exists vip_bingo_rooms_no_direct_insert on public.vip_bingo_rooms;
drop policy if exists vip_bingo_rooms_no_direct_update on public.vip_bingo_rooms;
drop policy if exists vip_bingo_rooms_no_direct_delete on public.vip_bingo_rooms;
drop policy if exists vip_bingo_players_no_direct_select on public.vip_bingo_players;
drop policy if exists vip_bingo_players_no_direct_insert on public.vip_bingo_players;
drop policy if exists vip_bingo_players_no_direct_update on public.vip_bingo_players;
drop policy if exists vip_bingo_players_no_direct_delete on public.vip_bingo_players;
drop policy if exists vip_roulette_rewards_no_direct_select on public.vip_roulette_rewards;
drop policy if exists vip_roulette_rewards_no_direct_insert on public.vip_roulette_rewards;
drop policy if exists vip_roulette_rewards_no_direct_update on public.vip_roulette_rewards;
drop policy if exists vip_roulette_rewards_no_direct_delete on public.vip_roulette_rewards;
drop policy if exists vip_roulette_spins_no_direct_select on public.vip_roulette_spins;
drop policy if exists vip_roulette_spins_no_direct_insert on public.vip_roulette_spins;
drop policy if exists vip_roulette_spins_no_direct_update on public.vip_roulette_spins;
drop policy if exists vip_roulette_spins_no_direct_delete on public.vip_roulette_spins;
drop policy if exists vip_social_presence_no_direct_select on public.vip_social_presence;
drop policy if exists vip_social_presence_no_direct_insert on public.vip_social_presence;
drop policy if exists vip_social_presence_no_direct_update on public.vip_social_presence;
drop policy if exists vip_social_presence_no_direct_delete on public.vip_social_presence;
drop policy if exists vip_events_no_direct_select on public.vip_events;
drop policy if exists vip_events_no_direct_insert on public.vip_events;
drop policy if exists vip_events_no_direct_update on public.vip_events;
drop policy if exists vip_events_no_direct_delete on public.vip_events;
drop policy if exists vip_event_rewards_no_direct_select on public.vip_event_rewards;
drop policy if exists vip_event_rewards_no_direct_insert on public.vip_event_rewards;
drop policy if exists vip_event_rewards_no_direct_update on public.vip_event_rewards;
drop policy if exists vip_event_rewards_no_direct_delete on public.vip_event_rewards;

revoke all on table public.vip_memberships from anon, authenticated;
revoke all on table public.vip_game_results from anon, authenticated;
revoke all on table public.vip_wallets from anon, authenticated;
revoke all on table public.vip_wallet_transactions from anon, authenticated;
revoke all on table public.vip_coin_conversions from anon, authenticated;
revoke all on table public.vip_bingo_rooms from anon, authenticated;
revoke all on table public.vip_bingo_players from anon, authenticated;
revoke all on table public.vip_roulette_rewards from anon, authenticated;
revoke all on table public.vip_roulette_spins from anon, authenticated;
revoke all on table public.vip_social_presence from anon, authenticated;
revoke all on table public.vip_events from anon, authenticated;
revoke all on table public.vip_event_rewards from anon, authenticated;
grant execute on function public.obtener_estado_vip(text, text) to anon, authenticated;
grant execute on function public.registrar_resultado_juego_vip(text, text, text, text, text, integer, jsonb, jsonb) to anon, authenticated;
grant execute on function public.obtener_billetera_vip(text, text) to anon, authenticated;
grant execute on function public.convertir_monedas_vip(text, text, bigint) to anon, authenticated;
grant execute on function public.obtener_historial_juegos_vip(text, text, text, integer) to anon, authenticated;
grant execute on function public.vip_bingo_crear_sala(text, text, text) to anon, authenticated;
grant execute on function public.vip_bingo_unirse_sala(text, text, text) to anon, authenticated;
grant execute on function public.vip_bingo_obtener_sala(text, text, text) to anon, authenticated;
grant execute on function public.vip_bingo_cantar_numero(text, text, text) to anon, authenticated;
grant execute on function public.vip_bingo_marcar_numero(text, text, text, integer) to anon, authenticated;
grant execute on function public.vip_bingo_reclamar(text, text, text) to anon, authenticated;
grant execute on function public.vip_roulette_obtener_estado(text, text) to anon, authenticated;
grant execute on function public.vip_roulette_girar(text, text) to anon, authenticated;
grant execute on function public.vip_social_ping(text, text, text) to anon, authenticated;
grant execute on function public.obtener_eventos_vip_activos(text, text) to anon, authenticated;
grant execute on function public.admin_guardar_evento_vip(text, bigint, text, text, text, timestamptz, timestamptz, boolean, text, jsonb, jsonb) to anon, authenticated;
grant execute on function public.admin_listar_eventos_vip(text) to anon, authenticated;
grant execute on function public.admin_cambiar_estado_evento_vip(text, bigint, boolean) to anon, authenticated;
grant execute on function public.admin_eliminar_evento_vip(text, bigint) to anon, authenticated;
grant execute on function public.admin_guardar_membresia_vip(text, text, boolean, timestamptz) to anon, authenticated;
grant execute on function public.admin_listar_membresias_vip(text) to anon, authenticated;
