create table if not exists public.estadisticas_logros (
  id bigint generated by default as identity primary key,
  usuario text not null,
  juego text not null,
  completados integer not null default 0,
  completados_sin_errores integer not null default 0,
  racha_completados_actual integer not null default 0,
  mejor_racha_completados integer not null default 0,
  racha_sin_errores_actual integer not null default 0,
  mejor_racha_sin_errores integer not null default 0,
  mejor_tiempo integer,
  tiempo_jugado_total integer not null default 0,
  racha_tiempo_jugado_actual integer not null default 0,
  mejor_racha_tiempo_jugado integer not null default 0,
  torneos_participados integer not null default 0,
  mejor_posicion_torneo integer,
  victorias_torneos integer not null default 0,
  racha_victorias_torneos_actual integer not null default 0,
  mejor_racha_victorias_torneos integer not null default 0,
  racha_top10_torneos_actual integer not null default 0,
  mejor_racha_top10_torneos integer not null default 0,
  top3_torneos integer not null default 0,
  racha_top3_torneos_actual integer not null default 0,
  mejor_racha_top3_torneos integer not null default 0,
  victorias_sin_errores integer not null default 0,
  ultima_posicion_torneo integer,
  top15_torneos integer not null default 0,
  cuartos_lugares integer not null default 0,
  posiciones_mejoradas integer not null default 0,
  max_posiciones_subidas integer not null default 0,
  mejores_historicas_superadas integer not null default 0,
  jugadores_mejor_rankeados_superados integer not null default 0,
  max_jugadores_mejor_rankeados_superados integer not null default 0,
  torneos_mismo_dia_fecha text,
  torneos_mismo_dia_actual integer not null default 0,
  mejor_torneos_mismo_dia integer not null default 0,
  memoria_errores_total integer not null default 0,
  memoria_min_errores_partida integer,
  memoria_max_errores_partida integer not null default 0,
  memoria_mejor_racha_pares integer not null default 0,
  memoria_mejor_racha_fallos integer not null default 0,
  memoria_pares_antes_1min integer not null default 0,
  memoria_max_intentos_partida integer not null default 0,
  memoria_mejor_movimientos integer,
  memoria_mejor_tiempo_sin_errores integer,
  memoria_menos_20_movimientos integer not null default 0,
  memoria_mejoras_tiempo integer not null default 0,
  memoria_fallo_ultimo_par integer not null default 0,
  memoria_acierto_tras_5_fallos integer not null default 0,
  memoria_par_menos_2s integer not null default 0,
  memoria_par_menos_20s integer not null default 0,
  memoria_acierto_tras_2_fallos integer not null default 0,
  memoria_par_sin_ver_previo integer not null default 0,
  memoria_sin_repetir_error_par integer not null default 0,
  memoria_partidas_ventana_inicio text,
  memoria_partidas_ventana_actual integer not null default 0,
  memoria_mejor_partidas_10min integer not null default 0,
  memoria_partidas_ventana_15_inicio text,
  memoria_partidas_ventana_15_actual integer not null default 0,
  memoria_mejor_partidas_15min integer not null default 0,
  memoria_primer_movimiento_par integer not null default 0,
  memoria_lineal integer not null default 0,
  memoria_sin_patron_repetido integer not null default 0,
  memoria_anticipacion integer not null default 0,
  memoria_sin_cartas_falladas_repetidas integer not null default 0,
  memoria_inicio_4_pares integer not null default 0,
  memoria_final_4_pares integer not null default 0,
  matematicas_total_correctas integer not null default 0,
  matematicas_sesiones_sin_errores integer not null default 0,
  matematicas_ejercicios_menos_15s integer not null default 0,
  matematicas_ejercicios_menos_14s integer not null default 0,
  matematicas_ejercicios_menos_13s integer not null default 0,
  matematicas_ejercicios_menos_12s integer not null default 0,
  matematicas_ejercicios_menos_11s integer not null default 0,
  matematicas_ejercicios_menos_10s integer not null default 0,
  matematicas_ejercicios_menos_9s integer not null default 0,
  matematicas_ejercicios_menos_8s integer not null default 0,
  matematicas_ejercicios_menos_7s integer not null default 0,
  matematicas_ejercicios_menos_6s integer not null default 0,
  matematicas_ejercicios_menos_5s integer not null default 0,
  matematicas_ejercicios_menos_4s integer not null default 0,
  matematicas_ejercicios_menos_3_5s integer not null default 0,
  matematicas_ejercicios_menos_3s integer not null default 0,
  matematicas_ejercicios_menos_2_5s integer not null default 0,
  matematicas_ejercicios_menos_2s integer not null default 0,
  matematicas_ejercicios_menos_1_8s integer not null default 0,
  matematicas_ejercicios_menos_1_5s integer not null default 0,
  matematicas_ejercicios_menos_1_2s integer not null default 0,
  matematicas_ejercicios_menos_1s integer not null default 0,
  matematicas_ejercicios_menos_0_8s integer not null default 0,
  matematicas_mejor_racha_correctas integer not null default 0,
  matematicas_mejor_racha_3s integer not null default 0,
  matematicas_mejor_racha_5s integer not null default 0,
  matematicas_mejor_correctas_60s integer not null default 0,
  flashmind_total_correctas integer not null default 0,
  flashmind_mejor_racha_correctas integer not null default 0,
  numcatch_total_aciertos integer not null default 0,
  numcatch_mejor_racha_aciertos integer not null default 0,
  numcatch_mejor_racha_aciertos_victoria integer not null default 0,
  numcatch_min_errores_victoria integer,
  numcatch_victorias_1_error integer not null default 0,
  numcatch_victorias_2_errores integer not null default 0,
  numcatch_victorias_menos_14_errores integer not null default 0,
  numcatch_racha_victorias_400_actual integer not null default 0,
  numcatch_mejor_racha_victorias_400 integer not null default 0,
  numcatch_racha_victorias_1200_actual integer not null default 0,
  numcatch_mejor_racha_victorias_1200 integer not null default 0,
  numcatch_racha_top3_sin_bajar_actual integer not null default 0,
  numcatch_mejor_racha_top3_sin_bajar integer not null default 0,
  numcatch_victoria_tras_fuera_podio integer not null default 0,
  domino_racha_invicto_actual integer not null default 0,
  domino_mejor_racha_invicto integer not null default 0,
  damas_racha_segundo_actual integer not null default 0,
  damas_mejor_racha_segundo integer not null default 0,
  damas_racha_tercero_actual integer not null default 0,
  damas_mejor_racha_tercero integer not null default 0,
  ajedrez_victorias_clasificatorias integer not null default 0,
  ajedrez_victorias_sin_perder_piezas integer not null default 0,
  ajedrez_mate_tras_sacrificar_reina integer not null default 0,
  ajedrez_final_menores_peones integer not null default 0,
  ajedrez_remontada_15_material integer not null default 0,
  ajedrez_dos_sacrificios_consecutivos integer not null default 0,
  ajedrez_victorias_80_movimientos integer not null default 0,
  ajedrez_rey_peon_vs_piezas integer not null default 0,
  ajedrez_derrota_mayor_rango integer not null default 0,
  ajedrez_racha_13_sin_errores integer not null default 0,
  ajedrez_jaque_5_turnos integer not null default 0,
  ajedrez_mate_dos_alfiles integer not null default 0,
  ajedrez_victoria_menos_10s integer not null default 0,
  ajedrez_mate_antes_15 integer not null default 0,
  ajedrez_castiga_3_errores integer not null default 0,
  ajedrez_captura_mayores_antes_mate integer not null default 0,
  ajedrez_victoria_sin_enrocar integer not null default 0,
  ajedrez_3_promociones integer not null default 0,
  ajedrez_apertura_actual text,
  ajedrez_racha_apertura_actual integer not null default 0,
  ajedrez_mejor_racha_apertura integer not null default 0,
  ajedrez_campeon_invicto integer not null default 0,
  ajedrez_racha_mate_actual integer not null default 0,
  ajedrez_mejor_racha_mate integer not null default 0,
  ajedrez_racha_aperturas_diferentes_actual integer not null default 0,
  ajedrez_mejor_racha_aperturas_diferentes integer not null default 0,
  ajedrez_aperturas_diferentes_historial text,
  ajedrez_racha_menos_25_movimientos_actual integer not null default 0,
  ajedrez_mejor_racha_menos_25_movimientos integer not null default 0,
  ajedrez_racha_sin_tablas_actual integer not null default 0,
  ajedrez_mejor_racha_sin_tablas integer not null default 0,
  ajedrez_racha_sacrificio_actual integer not null default 0,
  ajedrez_mejor_racha_sacrificio integer not null default 0,
  ajedrez_racha_sin_perder_torre_actual integer not null default 0,
  ajedrez_mejor_racha_sin_perder_torre integer not null default 0,
  ajedrez_racha_jaque_antes_10_actual integer not null default 0,
  ajedrez_mejor_racha_jaque_antes_10 integer not null default 0,
  ajedrez_racha_remontada_material_actual integer not null default 0,
  ajedrez_mejor_racha_remontada_material integer not null default 0,
  ajedrez_perdio_partida_previa boolean not null default false,
  ajedrez_racha_victoria_tras_derrota_actual integer not null default 0,
  ajedrez_mejor_racha_victoria_tras_derrota integer not null default 0,
  ultimo_tiempo integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (usuario, juego)
);

alter table public.estadisticas_logros
add column if not exists racha_completados_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_racha_completados integer not null default 0;

alter table public.estadisticas_logros
add column if not exists tiempo_jugado_total integer not null default 0;

alter table public.estadisticas_logros
add column if not exists racha_tiempo_jugado_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_racha_tiempo_jugado integer not null default 0;

alter table public.estadisticas_logros
add column if not exists torneos_participados integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_posicion_torneo integer;

alter table public.estadisticas_logros
add column if not exists victorias_torneos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists racha_victorias_torneos_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_racha_victorias_torneos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists racha_top10_torneos_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_racha_top10_torneos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists top3_torneos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists racha_top3_torneos_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_racha_top3_torneos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists victorias_sin_errores integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ultima_posicion_torneo integer;

alter table public.estadisticas_logros
add column if not exists top15_torneos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists cuartos_lugares integer not null default 0;

alter table public.estadisticas_logros
add column if not exists posiciones_mejoradas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists max_posiciones_subidas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejores_historicas_superadas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists jugadores_mejor_rankeados_superados integer not null default 0;

alter table public.estadisticas_logros
add column if not exists max_jugadores_mejor_rankeados_superados integer not null default 0;

alter table public.estadisticas_logros
add column if not exists torneos_mismo_dia_fecha text;

alter table public.estadisticas_logros
add column if not exists torneos_mismo_dia_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists mejor_torneos_mismo_dia integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_errores_total integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_min_errores_partida integer;

alter table public.estadisticas_logros
add column if not exists memoria_max_errores_partida integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_racha_pares integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_racha_fallos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_pares_antes_1min integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_max_intentos_partida integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_movimientos integer;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_tiempo_sin_errores integer;

alter table public.estadisticas_logros
add column if not exists memoria_menos_20_movimientos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejoras_tiempo integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_fallo_ultimo_par integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_acierto_tras_5_fallos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_par_menos_2s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_par_menos_20s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_acierto_tras_2_fallos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_par_sin_ver_previo integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_sin_repetir_error_par integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_partidas_ventana_inicio text;

alter table public.estadisticas_logros
add column if not exists memoria_partidas_ventana_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_partidas_10min integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_partidas_ventana_15_inicio text;

alter table public.estadisticas_logros
add column if not exists memoria_partidas_ventana_15_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_mejor_partidas_15min integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_primer_movimiento_par integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_lineal integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_sin_patron_repetido integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_anticipacion integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_sin_cartas_falladas_repetidas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_inicio_4_pares integer not null default 0;

alter table public.estadisticas_logros
add column if not exists memoria_final_4_pares integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_total_correctas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_sesiones_sin_errores integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_15s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_14s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_13s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_12s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_11s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_10s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_9s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_8s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_7s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_6s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_5s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_4s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_3_5s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_3s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_2_5s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_2s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_1_8s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_1_5s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_1_2s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_1s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_ejercicios_menos_0_8s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_mejor_racha_correctas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_mejor_racha_3s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_mejor_racha_5s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists matematicas_mejor_correctas_60s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists flashmind_total_correctas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists flashmind_mejor_racha_correctas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_total_aciertos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_mejor_racha_aciertos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_mejor_racha_aciertos_victoria integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_min_errores_victoria integer;

alter table public.estadisticas_logros
add column if not exists numcatch_victorias_1_error integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_victorias_2_errores integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_victorias_menos_14_errores integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_racha_victorias_400_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_mejor_racha_victorias_400 integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_racha_victorias_1200_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_mejor_racha_victorias_1200 integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_racha_top3_sin_bajar_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_mejor_racha_top3_sin_bajar integer not null default 0;

alter table public.estadisticas_logros
add column if not exists numcatch_victoria_tras_fuera_podio integer not null default 0;

alter table public.estadisticas_logros
add column if not exists domino_racha_invicto_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists domino_mejor_racha_invicto integer not null default 0;

alter table public.estadisticas_logros
add column if not exists damas_racha_segundo_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists damas_mejor_racha_segundo integer not null default 0;

alter table public.estadisticas_logros
add column if not exists damas_racha_tercero_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists damas_mejor_racha_tercero integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_victorias_clasificatorias integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_victorias_sin_perder_piezas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mate_tras_sacrificar_reina integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_final_menores_peones integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_remontada_15_material integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_dos_sacrificios_consecutivos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_victorias_80_movimientos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_rey_peon_vs_piezas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_derrota_mayor_rango integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_13_sin_errores integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_jaque_5_turnos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mate_dos_alfiles integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_victoria_menos_10s integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mate_antes_15 integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_castiga_3_errores integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_captura_mayores_antes_mate integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_victoria_sin_enrocar integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_3_promociones integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_apertura_actual text;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_apertura_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mejor_racha_apertura integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_campeon_invicto integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_mate_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mejor_racha_mate integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_aperturas_diferentes_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mejor_racha_aperturas_diferentes integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_aperturas_diferentes_historial text;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_menos_25_movimientos_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mejor_racha_menos_25_movimientos integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_sin_tablas_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mejor_racha_sin_tablas integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_sacrificio_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mejor_racha_sacrificio integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_sin_perder_torre_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mejor_racha_sin_perder_torre integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_jaque_antes_10_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mejor_racha_jaque_antes_10 integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_remontada_material_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mejor_racha_remontada_material integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_perdio_partida_previa boolean not null default false;

alter table public.estadisticas_logros
add column if not exists ajedrez_racha_victoria_tras_derrota_actual integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ajedrez_mejor_racha_victoria_tras_derrota integer not null default 0;

alter table public.estadisticas_logros
add column if not exists ultimo_tiempo integer;

create index if not exists estadisticas_logros_usuario_idx
on public.estadisticas_logros (usuario);

create index if not exists estadisticas_logros_juego_idx
on public.estadisticas_logros (juego);

create table if not exists public.temporadas_nivel (
  id text primary key,
  nombre text not null,
  activa boolean not null default false,
  fecha_inicio timestamptz not null default now(),
  fecha_fin timestamptz,
  created_at timestamptz not null default now()
);

insert into public.temporadas_nivel (id, nombre, activa)
values ('temporada-actual', 'Temporada actual', true)
on conflict (id) do nothing;

create table if not exists public.progreso_nivel (
  usuario_id text primary key,
  temporada_id text not null default 'temporada-actual' references public.temporadas_nivel(id),
  xp integer not null default 0 check (xp >= 0),
  nivel integer not null default 1 check (nivel between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recompensas_nivel (
  id bigint generated by default as identity primary key,
  nivel integer not null check (nivel between 1 and 100),
  tipo text not null check (tipo in ('titulo', 'medalla', 'estilo', 'logro', 'xp_bonus')),
  valor text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (nivel, tipo, valor)
);

create table if not exists public.historial_xp (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  accion text not null,
  accion_key text,
  xp_ganado integer not null check (xp_ganado > 0),
  detalle jsonb not null default '{}'::jsonb,
  fecha timestamptz not null default now(),
  unique (usuario_id, accion_key)
);

create table if not exists public.recompensas_desbloqueadas (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  nivel integer not null check (nivel between 1 and 100),
  recompensa_id bigint references public.recompensas_nivel(id),
  tipo text not null,
  valor text not null,
  fecha timestamptz not null default now(),
  unique (usuario_id, nivel, tipo, valor)
);

create or replace function public.xp_requerido_nivel(nivel_actual integer)
returns integer
language sql
immutable
as $$
  select case
    when nivel_actual >= 100 then 0
    else 100 + floor(power(greatest(nivel_actual - 1, 0), 1.45) * 35)::integer + ((nivel_actual - 1) * 15)
  end;
$$;

create or replace function public.calcular_nivel_por_xp(xp_total integer)
returns integer
language plpgsql
immutable
as $$
declare
  nivel_actual integer := 1;
  acumulado integer := 0;
  requisito integer;
begin
  while nivel_actual < 100 loop
    requisito := public.xp_requerido_nivel(nivel_actual);
    exit when greatest(xp_total, 0) < acumulado + requisito;
    acumulado := acumulado + requisito;
    nivel_actual := nivel_actual + 1;
  end loop;

  return nivel_actual;
end;
$$;

create or replace function public.actualizar_nivel_desde_xp()
returns trigger
language plpgsql
as $$
begin
  new.xp := greatest(coalesce(new.xp, 0), 0);
  new.nivel := public.calcular_nivel_por_xp(new.xp);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists progreso_nivel_calcular_nivel on public.progreso_nivel;
create trigger progreso_nivel_calcular_nivel
before insert or update of xp on public.progreso_nivel
for each row
execute function public.actualizar_nivel_desde_xp();

create index if not exists progreso_nivel_ranking_idx
on public.progreso_nivel (nivel desc, xp desc);

create index if not exists historial_xp_usuario_fecha_idx
on public.historial_xp (usuario_id, fecha desc);

create or replace view public.ranking_nivel as
select
  usuario_id,
  temporada_id,
  xp,
  nivel,
  rank() over (partition by temporada_id order by nivel desc, xp desc, updated_at asc) as posicion,
  updated_at
from public.progreso_nivel;

insert into public.recompensas_nivel (nivel, tipo, valor, metadata)
select
  nivel,
  case
    when nivel % 10 = 0 then 'titulo'
    when nivel % 5 = 0 then 'medalla'
    when nivel % 3 = 0 then 'estilo'
    else 'xp_bonus'
  end as tipo,
  case
    when nivel % 10 = 0 then
      (array['Novato', 'Aspirante', 'Competidor', 'Calculador', 'Estratega', 'Especialista', 'Veterano', 'Maestro', 'Campeon', 'Leyenda'])[(ceil(nivel / 10.0))::integer] || ' ' || nivel
    when nivel % 5 = 0 then 'Medalla nivel ' || nivel
    when nivel % 3 = 0 then 'Borde de perfil nivel ' || nivel
    else 'Bonus de temporada nivel ' || nivel
  end as valor,
  jsonb_build_object('season_pass', true)
from generate_series(1, 100) as nivel
on conflict (nivel, tipo, valor) do nothing;
create or replace function public.limpiar_datos_usuario_torneo(usuario_borrado text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  objetivo record;
begin
  if usuario_borrado is null or btrim(usuario_borrado) = '' then
    return;
  end if;

  for objetivo in
    select *
    from (values
      ('ranking', 'usuario'),
      ('ranking', 'usuario_id'),
      ('ranking_ajedrez', 'usuario'),
      ('ranking_ajedrez', 'usuario_id'),
      ('ranking_domino', 'usuario'),
      ('ranking_domino', 'usuario_id'),
      ('ranking_damas', 'usuario'),
      ('ranking_damas', 'usuario_id'),
      ('partidas', 'usuario'),
      ('partidas', 'usuario_id'),
      ('estadisticas_logros', 'usuario'),
      ('progreso_nivel', 'usuario_id'),
      ('historial_xp', 'usuario_id'),
      ('recompensas_desbloqueadas', 'usuario_id')
    ) as pendientes(tabla, columna)
    where to_regclass('public.' || pendientes.tabla) is not null
      and exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = pendientes.tabla
          and column_name = pendientes.columna
      )
  loop
    execute format('delete from public.%I where %I = $1', objetivo.tabla, objetivo.columna)
    using usuario_borrado;
  end loop;
end;
$$;

create or replace function public.limpiar_datos_usuario_torneo_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.limpiar_datos_usuario_torneo(old.usuario);
  return old;
end;
$$;

do $$
begin
  if to_regclass('public.usuarios') is not null
    and exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'usuarios'
        and column_name = 'usuario'
    )
  then
    execute 'drop trigger if exists usuarios_limpiar_datos_torneo on public.usuarios';
    execute '
      create trigger usuarios_limpiar_datos_torneo
      after delete on public.usuarios
      for each row
      execute function public.limpiar_datos_usuario_torneo_trigger()
    ';
  end if;
end;
$$;

create or replace function public.validar_admin_torneo(p_clave text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  valido boolean := false;
begin
  if to_regclass('public.configuracion') is null then
    return false;
  end if;

  execute
    'select coalesce(trim(clave_admin::text) = trim($1), false)
     from public.configuracion
     where id = 1'
  into valido
  using p_clave;

  return coalesce(valido, false);
exception
  when others then
    return false;
end;
$$;

create or replace function public.admin_guardar_historico_ranking(p_juego text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  es_puntaje boolean := p_juego in ('matematicas', 'flashmind', 'numcatch');
  orden text := case when p_juego in ('matematicas', 'flashmind', 'numcatch') then 'desc' else 'asc' end;
  desde timestamptz := now() - interval '12 hours';
begin
  if p_juego is null or btrim(p_juego) = '' then
    return;
  end if;

  if to_regclass('public.estado_torneo') is not null then
    begin
      execute 'select coalesce(inicio_torneo, now() - interval ''12 hours'') from public.estado_torneo where id = 1'
      into desde;
    exception
      when others then
        desde := now() - interval '12 hours';
    end;
  end if;

  if to_regclass('public.ranking') is not null and to_regclass('public.partidas') is not null then
    begin
      execute format(
        'insert into public.partidas (usuario, usuario_id, juego, puntos, tiempo, posicion)
         select usuario, null, juego,
           case when $2 then coalesce(tiempo, 0) else 0 end,
           case when $2 then 0 else coalesce(tiempo, 0) end,
           row_number() over (order by tiempo %s)
         from public.ranking r
         where juego = $1
           and coalesce(invalido, false) = false
           and not exists (
             select 1
             from public.partidas p
             where p.usuario = r.usuario
               and p.juego = r.juego
               and p.fecha >= $3
               and (($2 and p.puntos = coalesce(r.tiempo, 0)) or (not $2 and p.tiempo = coalesce(r.tiempo, 0)))
           )',
        orden
      )
      using p_juego, es_puntaje, desde;
    exception
      when others then
        null;
    end;
  end if;
end;
$$;

create or replace function public.admin_limpiar_ranking_temporal(p_clave text, p_juego text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  tabla_extra text := case p_juego
    when 'ajedrez' then 'ranking_ajedrez'
    when 'domino' then 'ranking_domino'
    when 'damas' then 'ranking_damas'
    else null
  end;
begin
  if not public.validar_admin_torneo(p_clave) then
    return false;
  end if;

  perform public.admin_guardar_historico_ranking(p_juego);

  if to_regclass('public.ranking') is not null then
    execute 'delete from public.ranking where juego = $1' using p_juego;
  end if;

  if tabla_extra is not null and to_regclass('public.' || tabla_extra) is not null then
    execute format('delete from public.%I where usuario is not null', tabla_extra);
  end if;

  return true;
end;
$$;

create or replace function public.admin_eliminar_jugador_ranking(p_clave text, p_usuario text, p_juego text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  tabla_extra text := case p_juego
    when 'ajedrez' then 'ranking_ajedrez'
    when 'domino' then 'ranking_domino'
    when 'damas' then 'ranking_damas'
    else null
  end;
begin
  if not public.validar_admin_torneo(p_clave) then
    return false;
  end if;

  if to_regclass('public.ranking') is not null then
    execute 'delete from public.ranking where usuario = $1 and juego = $2' using p_usuario, p_juego;
  end if;

  if tabla_extra is not null and to_regclass('public.' || tabla_extra) is not null then
    execute format('delete from public.%I where usuario = $1', tabla_extra) using p_usuario;
  end if;

  return true;
end;
$$;

create or replace function public.admin_iniciar_torneo(p_clave text, p_juego text, p_numcatch_condicion text default 'multiplos_3')
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  estado_actual text;
  tiene_numcatch boolean := false;
begin
  if not public.validar_admin_torneo(p_clave) then
    return false;
  end if;

  if to_regclass('public.estado_torneo') is null then
    return false;
  end if;

  execute 'select estado from public.estado_torneo where id = 1' into estado_actual;
  if estado_actual = 'iniciado' then
    return false;
  end if;

  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'estado_torneo'
      and column_name = 'numcatch_condicion'
  ) into tiene_numcatch;

  if p_juego = 'numcatch' and tiene_numcatch then
    execute
      'update public.estado_torneo
       set estado = ''iniciado'', juego_actual = $1, inicio_torneo = now(), numcatch_condicion = $2
       where id = 1'
    using p_juego, coalesce(p_numcatch_condicion, 'multiplos_3');
  else
    execute
      'update public.estado_torneo
       set estado = ''iniciado'', juego_actual = $1, inicio_torneo = now()
       where id = 1'
    using p_juego;
  end if;

  return true;
end;
$$;

create or replace function public.admin_detener_torneo(p_clave text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validar_admin_torneo(p_clave) then
    return false;
  end if;

  if to_regclass('public.estado_torneo') is not null then
    execute 'update public.estado_torneo set estado = ''espera'' where id = 1';
  end if;

  return true;
end;
$$;

create or replace function public.admin_borrar_ranking_semana(p_clave text, p_juego text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validar_admin_torneo(p_clave) then
    return false;
  end if;

  if to_regclass('public.partidas') is not null then
    execute
      'delete from public.partidas
       where juego = $1
         and fecha >= date_trunc(''week'', now())'
    using p_juego;
  end if;

  return true;
end;
$$;

create or replace function public.admin_borrar_ranking_victorias(p_clave text, p_juego text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validar_admin_torneo(p_clave) then
    return false;
  end if;

  if to_regclass('public.partidas') is not null then
    execute 'update public.partidas set posicion = 0 where juego = $1 and posicion = 1' using p_juego;
  end if;

  return true;
end;
$$;

create or replace function public.admin_borrar_ranking_global(p_clave text, p_juego text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validar_admin_torneo(p_clave) then
    return false;
  end if;

  perform public.admin_limpiar_ranking_temporal(p_clave, p_juego);

  if to_regclass('public.partidas') is not null then
    execute 'delete from public.partidas where juego = $1 and usuario is not null' using p_juego;
  end if;

  return true;
end;
$$;

create or replace function public.admin_reset_total(p_clave text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  tabla text;
begin
  if not public.validar_admin_torneo(p_clave) then
    return false;
  end if;

  foreach tabla in array array[
    'ranking',
    'ranking_ajedrez',
    'ranking_domino',
    'ranking_damas',
    'partidas',
    'estadisticas_logros'
  ]
  loop
    if to_regclass('public.' || tabla) is not null then
      execute format('delete from public.%I where usuario is not null', tabla);
    end if;
  end loop;

  if to_regclass('public.usuarios') is not null then
    execute 'update public.usuarios set tablero_id = null, cartas_memoria = null where usuario is not null';
  end if;

  return true;
end;
$$;

do $$
begin
  if to_regclass('public.configuracion') is not null then
    execute 'revoke all on table public.configuracion from anon, authenticated';
  end if;
end;
$$;

grant execute on function public.validar_admin_torneo(text) to anon, authenticated;
grant execute on function public.admin_limpiar_ranking_temporal(text, text) to anon, authenticated;
grant execute on function public.admin_eliminar_jugador_ranking(text, text, text) to anon, authenticated;
grant execute on function public.admin_iniciar_torneo(text, text, text) to anon, authenticated;
grant execute on function public.admin_detener_torneo(text) to anon, authenticated;
grant execute on function public.admin_borrar_ranking_semana(text, text) to anon, authenticated;
grant execute on function public.admin_borrar_ranking_victorias(text, text) to anon, authenticated;
grant execute on function public.admin_borrar_ranking_global(text, text) to anon, authenticated;
grant execute on function public.admin_reset_total(text) to anon, authenticated;

create or replace function public.login_usuario_torneo(p_usuario text, p_codigo text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  codigo_limpio text := btrim(coalesce(p_codigo, ''));
  codigo_usuario text;
  codigo_disponible boolean := false;
begin
  if usuario_limpio = '' or codigo_limpio = '' then
    return jsonb_build_object('ok', false, 'mensaje', 'Completa los campos');
  end if;

  if to_regclass('public.usuarios') is null or to_regclass('public.codigos_invitacion') is null then
    return jsonb_build_object('ok', false, 'mensaje', 'La base de datos no esta lista para iniciar sesion');
  end if;

  execute 'select codigo::text from public.usuarios where usuario = $1 limit 1'
  into codigo_usuario
  using usuario_limpio;

  if codigo_usuario is not null then
    if codigo_usuario = codigo_limpio then
      return jsonb_build_object('ok', true, 'mensaje', 'Entrada correcta');
    end if;

    return jsonb_build_object('ok', false, 'mensaje', 'Ese apodo ya esta en uso con otro codigo');
  end if;

  execute
    'select exists (
       select 1
       from public.codigos_invitacion
       where codigo = $1
         and coalesce(usado, false) = false
     )'
  into codigo_disponible
  using codigo_limpio;

  if not coalesce(codigo_disponible, false) then
    return jsonb_build_object('ok', false, 'mensaje', 'Codigo invalido o ya usado');
  end if;

  execute 'insert into public.usuarios (usuario, codigo) values ($1, $2)'
  using usuario_limpio, codigo_limpio;

  execute 'update public.codigos_invitacion set usado = true where codigo = $1'
  using codigo_limpio;

  return jsonb_build_object('ok', true, 'mensaje', 'Usuario creado');
exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'mensaje', 'Ese apodo o codigo ya fue usado');
  when others then
    return jsonb_build_object('ok', false, 'mensaje', 'No se pudo iniciar sesion');
end;
$$;

grant execute on function public.login_usuario_torneo(text, text) to anon, authenticated;

do $$
declare
  tabla text;
  columnas_usuarios_select text;
  columnas_usuarios_update text;
  tablas_publicas text[] := array[
    'ranking',
    'ranking_ajedrez',
    'ranking_domino',
    'ranking_damas',
    'partidas',
    'estadisticas_logros',
    'temporadas_nivel',
    'progreso_nivel',
    'recompensas_nivel',
    'historial_xp',
    'recompensas_desbloqueadas',
    'usuarios',
    'estado_torneo',
    'tableros'
  ];
begin
  foreach tabla in array tablas_publicas
  loop
    if to_regclass('public.' || tabla) is not null then
      execute format('alter table public.%I enable row level security', tabla);

      execute format('drop policy if exists %I on public.%I', tabla || '_anon_select', tabla);
      execute format(
        'create policy %I on public.%I for select to anon, authenticated using (true)',
        tabla || '_anon_select',
        tabla
      );

      execute format('drop policy if exists %I on public.%I', tabla || '_anon_insert', tabla);
      execute format(
        'create policy %I on public.%I for insert to anon, authenticated with check (true)',
        tabla || '_anon_insert',
        tabla
      );

      execute format('drop policy if exists %I on public.%I', tabla || '_anon_update', tabla);
      execute format(
        'create policy %I on public.%I for update to anon, authenticated using (true) with check (true)',
        tabla || '_anon_update',
        tabla
      );
    end if;
  end loop;

  foreach tabla in array array['ranking', 'ranking_ajedrez', 'ranking_domino', 'ranking_damas']
  loop
    if to_regclass('public.' || tabla) is not null then
      execute format('drop policy if exists %I on public.%I', tabla || '_anon_delete', tabla);
      execute format(
        'create policy %I on public.%I for delete to anon, authenticated using (true)',
        tabla || '_anon_delete',
        tabla
      );
    end if;
  end loop;

  foreach tabla in array array['configuracion', 'codigos_invitacion']
  loop
    if to_regclass('public.' || tabla) is not null then
      execute format('alter table public.%I enable row level security', tabla);
      execute format('revoke all on table public.%I from anon, authenticated', tabla);
    end if;
  end loop;

  if to_regclass('public.usuarios') is not null then
    execute 'revoke all on table public.usuarios from anon, authenticated';

    select string_agg(quote_ident(column_name), ', ')
    into columnas_usuarios_select
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'usuarios'
      and column_name in ('id', 'usuario', 'tablero_id', 'cartas_memoria');

    if columnas_usuarios_select is not null then
      execute 'grant select (' || columnas_usuarios_select || ') on public.usuarios to anon, authenticated';
    end if;

    select string_agg(quote_ident(column_name), ', ')
    into columnas_usuarios_update
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'usuarios'
      and column_name in ('tablero_id', 'cartas_memoria');

    if columnas_usuarios_update is not null then
      execute 'grant update (' || columnas_usuarios_update || ') on public.usuarios to anon, authenticated';
    end if;
  end if;
end;
$$;
