-- Sistema VIP base para GameWorld.
-- Ejecutar en Supabase SQL Editor despues de las migraciones principales.

create table if not exists public.vip_memberships (
  id bigint generated by default as identity primary key,
  usuario_id text not null unique,
  is_active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vip_memberships_usuario_id_check check (btrim(usuario_id) <> '')
);

create index if not exists vip_memberships_active_idx
on public.vip_memberships (is_active, expires_at);

create table if not exists public.vip_game_results (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  game_key text not null,
  game_title text not null,
  mode text,
  score integer not null default 0,
  metrics jsonb not null default '{}'::jsonb,
  rewards jsonb not null default '{}'::jsonb,
  origin text not null default 'vip',
  created_at timestamptz not null default now(),
  constraint vip_game_results_usuario_check check (btrim(usuario_id) <> ''),
  constraint vip_game_results_game_key_check check (btrim(game_key) <> ''),
  constraint vip_game_results_score_check check (score >= 0),
  constraint vip_game_results_origin_check check (origin = 'vip')
);

create index if not exists vip_game_results_usuario_idx
on public.vip_game_results (usuario_id, created_at desc);

create index if not exists vip_game_results_game_idx
on public.vip_game_results (game_key, score desc, created_at desc);

create or replace function public.vip_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists vip_memberships_touch_updated_at on public.vip_memberships;

create trigger vip_memberships_touch_updated_at
before update on public.vip_memberships
for each row
execute function public.vip_touch_updated_at();

create or replace function public.obtener_estado_vip(p_usuario text, p_codigo text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  codigo_limpio text := btrim(coalesce(p_codigo, ''));
  codigo_usuario text;
  membresia record;
  expirado boolean := false;
begin
  if usuario_limpio = '' then
    return jsonb_build_object('ok', false, 'is_active', false, 'mensaje', 'Inicia sesion para entrar a la Zona VIP.');
  end if;

  if to_regclass('public.usuarios') is null then
    return jsonb_build_object('ok', false, 'is_active', false, 'mensaje', 'No se pudo validar tu usuario.');
  end if;

  execute 'select codigo::text from public.usuarios where usuario = $1 limit 1'
  into codigo_usuario
  using usuario_limpio;

  if codigo_usuario is null then
    return jsonb_build_object('ok', false, 'is_active', false, 'mensaje', 'Inicia sesion para entrar a la Zona VIP.');
  end if;

  if codigo_limpio = '' then
    return jsonb_build_object('ok', false, 'is_active', false, 'mensaje', 'Vuelve a iniciar sesion para validar tu acceso VIP.');
  end if;

  if codigo_usuario <> codigo_limpio then
    return jsonb_build_object('ok', false, 'is_active', false, 'mensaje', 'No se pudo validar tu sesion VIP.');
  end if;

  select *
  into membresia
  from public.vip_memberships
  where usuario_id = usuario_limpio
  limit 1;

  if not found then
    return jsonb_build_object(
      'ok', true,
      'is_active', false,
      'is_vip', false,
      'expires_at', null,
      'mensaje', 'No eres VIP todavia. Puedes comprar el acceso VIP desde la tienda.'
    );
  end if;

  expirado := membresia.expires_at is not null and membresia.expires_at <= now();

  return jsonb_build_object(
    'ok', true,
    'is_active', membresia.is_active and not expirado,
    'is_vip', membresia.is_active and not expirado,
    'expires_at', membresia.expires_at,
    'mensaje', case
      when membresia.is_active and not expirado then 'Acceso VIP activo.'
      when expirado then 'Tu acceso VIP expiro.'
      else 'Tu acceso VIP no esta activo.'
    end
  );
end;
$$;

create or replace function public.registrar_resultado_juego_vip(
  p_usuario text,
  p_codigo text default null,
  p_game_key text default null,
  p_game_title text default null,
  p_mode text default null,
  p_score integer default 0,
  p_metrics jsonb default '{}'::jsonb,
  p_rewards jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  game_key_limpio text := lower(btrim(coalesce(p_game_key, '')));
  game_title_limpio text := btrim(coalesce(p_game_title, p_game_key, 'Juego VIP'));
  resultado public.vip_game_results%rowtype;
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object(
      'ok', false,
      'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.')
    );
  end if;

  if game_key_limpio = '' then
    return jsonb_build_object('ok', false, 'mensaje', 'Juego VIP invalido.');
  end if;

  insert into public.vip_game_results (
    usuario_id,
    game_key,
    game_title,
    mode,
    score,
    metrics,
    rewards,
    origin
  )
  values (
    usuario_limpio,
    game_key_limpio,
    game_title_limpio,
    nullif(btrim(coalesce(p_mode, '')), ''),
    greatest(0, coalesce(p_score, 0)),
    coalesce(p_metrics, '{}'::jsonb),
    coalesce(p_rewards, '{}'::jsonb),
    'vip'
  )
  returning *
  into resultado;

  return jsonb_build_object(
    'ok', true,
    'result', jsonb_build_object(
      'id', resultado.id,
      'usuario_id', resultado.usuario_id,
      'game_key', resultado.game_key,
      'game_title', resultado.game_title,
      'mode', resultado.mode,
      'score', resultado.score,
      'metrics', resultado.metrics,
      'rewards', resultado.rewards,
      'origin', resultado.origin,
      'created_at', resultado.created_at
    )
  );
end;
$$;

create or replace function public.obtener_historial_juegos_vip(
  p_usuario text,
  p_codigo text default null,
  p_game_key text default null,
  p_limit integer default 8
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estado jsonb;
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
  game_key_limpio text := nullif(lower(btrim(coalesce(p_game_key, ''))), '');
  limite integer := least(30, greatest(1, coalesce(p_limit, 8)));
begin
  estado := public.obtener_estado_vip(usuario_limpio, p_codigo);

  if coalesce((estado->>'is_vip')::boolean, false) is not true then
    return jsonb_build_object(
      'ok', false,
      'mensaje', coalesce(estado->>'mensaje', 'No se pudo validar tu acceso VIP.'),
      'items', '[]'::jsonb
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'items',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', id,
          'usuario_id', usuario_id,
          'game_key', game_key,
          'game_title', game_title,
          'mode', mode,
          'score', score,
          'metrics', metrics,
          'rewards', rewards,
          'origin', origin,
          'created_at', created_at
        )
        order by created_at desc
      )
      from (
        select *
        from public.vip_game_results
        where usuario_id = usuario_limpio
          and (game_key_limpio is null or game_key = game_key_limpio)
        order by created_at desc
        limit limite
      ) recientes
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_guardar_membresia_vip(
  p_clave text,
  p_usuario text,
  p_activo boolean default true,
  p_expires_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  usuario_limpio text := btrim(coalesce(p_usuario, ''));
begin
  if not public.validar_admin_torneo(p_clave) then
    return jsonb_build_object('ok', false, 'mensaje', 'Clave admin invalida');
  end if;

  if usuario_limpio = '' or to_regclass('public.usuarios') is null then
    return jsonb_build_object('ok', false, 'mensaje', 'Usuario invalido');
  end if;

  if not exists (select 1 from public.usuarios where usuario = usuario_limpio) then
    return jsonb_build_object('ok', false, 'mensaje', 'El usuario no existe');
  end if;

  insert into public.vip_memberships (usuario_id, is_active, expires_at)
  values (usuario_limpio, coalesce(p_activo, true), p_expires_at)
  on conflict (usuario_id) do update
  set is_active = excluded.is_active,
      expires_at = excluded.expires_at,
      updated_at = now();

  return jsonb_build_object('ok', true, 'mensaje', 'Membresia VIP guardada');
end;
$$;

create or replace function public.admin_listar_membresias_vip(p_clave text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validar_admin_torneo(p_clave) then
    return jsonb_build_object('ok', false, 'mensaje', 'Clave admin invalida', 'items', '[]'::jsonb);
  end if;

  return jsonb_build_object(
    'ok', true,
    'items',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'usuario_id', usuario_id,
          'is_active', is_active,
          'expires_at', expires_at,
          'created_at', created_at,
          'updated_at', updated_at,
          'is_valid', is_active and (expires_at is null or expires_at > now())
        )
        order by updated_at desc
      )
      from public.vip_memberships
    ), '[]'::jsonb)
  );
end;
$$;

alter table public.vip_memberships enable row level security;
alter table public.vip_game_results enable row level security;

drop policy if exists vip_memberships_no_direct_select on public.vip_memberships;
drop policy if exists vip_memberships_no_direct_insert on public.vip_memberships;
drop policy if exists vip_memberships_no_direct_update on public.vip_memberships;
drop policy if exists vip_memberships_no_direct_delete on public.vip_memberships;
drop policy if exists vip_game_results_no_direct_select on public.vip_game_results;
drop policy if exists vip_game_results_no_direct_insert on public.vip_game_results;
drop policy if exists vip_game_results_no_direct_update on public.vip_game_results;
drop policy if exists vip_game_results_no_direct_delete on public.vip_game_results;

revoke all on table public.vip_memberships from anon, authenticated;
revoke all on table public.vip_game_results from anon, authenticated;
grant execute on function public.obtener_estado_vip(text, text) to anon, authenticated;
grant execute on function public.registrar_resultado_juego_vip(text, text, text, text, text, integer, jsonb, jsonb) to anon, authenticated;
grant execute on function public.obtener_historial_juegos_vip(text, text, text, integer) to anon, authenticated;
grant execute on function public.admin_guardar_membresia_vip(text, text, boolean, timestamptz) to anon, authenticated;
grant execute on function public.admin_listar_membresias_vip(text) to anon, authenticated;
