-- Tablas opcionales para activar el chat social del perfil competitivo.
-- No cambia autenticacion ni conexiones existentes.

create table if not exists public.chat_global (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  usuario text not null,
  mensaje text not null check (char_length(mensaje) <= 280),
  nivel integer not null default 1,
  rango text not null default 'Novato',
  created_at timestamptz not null default now()
);

create index if not exists chat_global_created_at_idx
  on public.chat_global (created_at desc);

alter table public.chat_global enable row level security;

drop policy if exists "chat_global_select_all" on public.chat_global;
create policy "chat_global_select_all"
  on public.chat_global for select
  using (true);

drop policy if exists "chat_global_insert_all" on public.chat_global;
create policy "chat_global_insert_all"
  on public.chat_global for insert
  with check (true);

do $$
begin
  alter publication supabase_realtime add table public.chat_global;
exception
  when duplicate_object then null;
end $$;

create table if not exists public.chat_privado (
  id bigint generated by default as identity primary key,
  remitente text not null,
  destinatario text not null,
  usuario_id text not null,
  usuario text not null,
  mensaje text not null check (char_length(mensaje) <= 280),
  nivel integer not null default 1,
  rango text not null default 'Novato',
  leido boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists chat_privado_conversacion_idx
  on public.chat_privado (remitente, destinatario, created_at desc);

alter table public.chat_privado enable row level security;

drop policy if exists "chat_privado_select_all" on public.chat_privado;
create policy "chat_privado_select_all"
  on public.chat_privado for select
  using (true);

drop policy if exists "chat_privado_insert_all" on public.chat_privado;
create policy "chat_privado_insert_all"
  on public.chat_privado for insert
  with check (true);

do $$
begin
  alter publication supabase_realtime add table public.chat_privado;
exception
  when duplicate_object then null;
end $$;
