create table if not exists public.estadisticas_logros (
  id bigint generated by default as identity primary key,
  usuario text not null,
  juego text not null,
  completados integer not null default 0,
  completados_sin_errores integer not null default 0,
  racha_sin_errores_actual integer not null default 0,
  mejor_racha_sin_errores integer not null default 0,
  mejor_tiempo integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (usuario, juego)
);

create index if not exists estadisticas_logros_usuario_idx
on public.estadisticas_logros (usuario);

create index if not exists estadisticas_logros_juego_idx
on public.estadisticas_logros (juego);
