-- Fase 1: infraestructura segura para pagos reales con Wompi.
-- Aplica este archivo despues de supabase-rankings.sql, supabase-experiencia-tienda.sql
-- y supabase-vip.sql, porque reutiliza usuario_monedas, usuario_boosters,
-- usuario_cosmeticos, vip_memberships y progreso_nivel.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'tienda_producto_tipo') then
    create type public.tienda_producto_tipo as enum (
      'monedas',
      'vip',
      'booster_xp',
      'booster_monedas',
      'cosmetico',
      'experiencia'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'tienda_compra_estado') then
    create type public.tienda_compra_estado as enum (
      'pendiente',
      'pagado',
      'entregado',
      'fallido',
      'cancelado',
      'expirado'
    );
  end if;
end $$;

create table if not exists public.productos_tienda (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  nombre text not null,
  descripcion text,
  tipo public.tienda_producto_tipo not null,
  precio_cop integer not null check (precio_cop > 0),
  moneda text not null default 'COP' check (moneda = 'COP'),
  activo boolean not null default true,
  orden integer not null default 100,
  reward_config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint productos_tienda_slug_check check (slug ~ '^[a-z0-9][a-z0-9_-]*$')
);

create table if not exists public.compras (
  id uuid primary key default gen_random_uuid(),
  usuario_id text not null,
  producto_id uuid not null references public.productos_tienda(id),
  estado public.tienda_compra_estado not null default 'pendiente',
  precio_cop_snapshot integer not null check (precio_cop_snapshot > 0),
  moneda text not null default 'COP' check (moneda = 'COP'),
  wompi_reference text not null unique,
  wompi_transaction_id text unique,
  wompi_status text,
  wompi_payment_method text,
  checkout_url text,
  metadata jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  delivered_at timestamptz,
  failed_at timestamptz,
  expires_at timestamptz not null default (now() + interval '2 hours'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint compras_usuario_id_check check (btrim(usuario_id) <> ''),
  constraint compras_wompi_reference_check check (btrim(wompi_reference) <> '')
);

create table if not exists public.historial_entregas (
  id bigint generated by default as identity primary key,
  compra_id uuid not null unique references public.compras(id) on delete cascade,
  usuario_id text not null,
  producto_id uuid not null references public.productos_tienda(id),
  tipo public.tienda_producto_tipo not null,
  resultado jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.wompi_eventos (
  id bigint generated by default as identity primary key,
  event_id text,
  transaction_id text,
  reference text,
  event_type text not null,
  payload jsonb not null,
  signature_valid boolean not null default false,
  processed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists productos_tienda_activos_idx
on public.productos_tienda (activo, orden, tipo);

create index if not exists compras_usuario_fecha_idx
on public.compras (usuario_id, created_at desc);

create index if not exists compras_estado_idx
on public.compras (estado, created_at desc);

create index if not exists wompi_eventos_reference_idx
on public.wompi_eventos (reference, created_at desc);

alter table public.productos_tienda enable row level security;
alter table public.compras enable row level security;
alter table public.historial_entregas enable row level security;
alter table public.wompi_eventos enable row level security;

drop policy if exists productos_tienda_public_select on public.productos_tienda;
create policy productos_tienda_public_select
on public.productos_tienda
for select
to anon, authenticated
using (activo = true);

revoke insert, update, delete on table public.productos_tienda from anon, authenticated;
revoke all on table public.compras from anon, authenticated;
revoke all on table public.historial_entregas from anon, authenticated;
revoke all on table public.wompi_eventos from anon, authenticated;
grant select on table public.productos_tienda to anon, authenticated;

create or replace function public.tienda_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists productos_tienda_touch_updated_at on public.productos_tienda;
create trigger productos_tienda_touch_updated_at
before update on public.productos_tienda
for each row execute function public.tienda_touch_updated_at();

drop trigger if exists compras_touch_updated_at on public.compras;
create trigger compras_touch_updated_at
before update on public.compras
for each row execute function public.tienda_touch_updated_at();

create or replace function public.tienda_entregar_compra_pagada(p_compra_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  compra public.compras%rowtype;
  producto public.productos_tienda%rowtype;
  cfg jsonb;
  tipo text;
  cantidad bigint;
  bonus bigint;
  total_monedas bigint;
  dias integer;
  multiplicador numeric(3,1);
  duracion_minutos integer;
  inicio timestamptz := now();
  fin timestamptz;
  item_id text;
  item_tipo text;
  item_rareza text;
  xp_resultado jsonb := '{}'::jsonb;
  entrega jsonb := '{}'::jsonb;
begin
  select *
  into compra
  from public.compras
  where id = p_compra_id
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'mensaje', 'Compra no encontrada.');
  end if;

  if compra.estado not in ('pagado', 'entregado') then
    return jsonb_build_object('ok', false, 'mensaje', 'La compra no esta pagada.', 'estado', compra.estado);
  end if;

  if compra.delivered_at is not null or compra.estado = 'entregado' then
    return jsonb_build_object('ok', true, 'mensaje', 'Compra ya entregada.', 'alreadyDelivered', true);
  end if;

  select *
  into producto
  from public.productos_tienda
  where id = compra.producto_id
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'mensaje', 'Producto no encontrado.');
  end if;

  cfg := producto.reward_config;
  tipo := producto.tipo::text;

  perform pg_advisory_xact_lock(hashtextextended('tienda:entrega:' || compra.id::text, 0));

  if exists (select 1 from public.historial_entregas where compra_id = compra.id) then
    update public.compras
    set estado = 'entregado',
        delivered_at = coalesce(delivered_at, now())
    where id = compra.id;

    return jsonb_build_object('ok', true, 'mensaje', 'Compra ya tenia entrega registrada.', 'alreadyDelivered', true);
  end if;

  if tipo = 'monedas' then
    cantidad := greatest(0, coalesce((cfg->>'cantidad')::bigint, 0));
    bonus := greatest(0, coalesce((cfg->>'bonus')::bigint, 0));
    total_monedas := cantidad + bonus;

    if total_monedas <= 0 then
      raise exception 'Config de monedas invalida';
    end if;

    insert into public.usuario_monedas (usuario_id, saldo)
    values (compra.usuario_id, total_monedas)
    on conflict (usuario_id) do update
      set saldo = public.usuario_monedas.saldo + excluded.saldo,
          updated_at = now();

    entrega := jsonb_build_object('monedas', total_monedas, 'cantidad', cantidad, 'bonus', bonus);

  elsif tipo = 'vip' then
    dias := nullif((cfg->>'dias')::integer, 0);

    insert into public.vip_memberships (usuario_id, is_active, expires_at)
    values (
      compra.usuario_id,
      true,
      case
        when dias is null then null
        else now() + (dias * interval '1 day')
      end
    )
    on conflict (usuario_id) do update
      set is_active = true,
          expires_at = case
            when excluded.expires_at is null then null
            when public.vip_memberships.is_active
              and public.vip_memberships.expires_at is not null
              and public.vip_memberships.expires_at > now()
              then public.vip_memberships.expires_at + (dias * interval '1 day')
            else excluded.expires_at
          end,
          updated_at = now();

    entrega := jsonb_build_object('vipDias', dias, 'permanente', dias is null);

  elsif tipo in ('booster_xp', 'booster_monedas') then
    multiplicador := round(greatest(1.2, least(8.0, coalesce((cfg->>'multiplicador')::numeric, 1.2)))::numeric, 1);
    duracion_minutos := greatest(1, coalesce((cfg->>'duracion_minutos')::integer, 60));
    item_id := coalesce(nullif(cfg->>'booster_id', ''), producto.slug);
    fin := inicio + (duracion_minutos * interval '1 minute');

    update public.usuario_boosters
    set activo = false
    where usuario_id = compra.usuario_id
      and fecha_fin > now()
      and (
        (tipo = 'booster_xp' and booster_id not like 'coins_%' and booster_id not like 'admin_coins_%')
        or (tipo = 'booster_monedas' and (booster_id like 'coins_%' or booster_id like 'admin_coins_%'))
      );

    insert into public.usuario_boosters (usuario_id, booster_id, multiplicador, fecha_inicio, fecha_fin, activo)
    values (compra.usuario_id, item_id, multiplicador, inicio, fin, true);

    entrega := jsonb_build_object('boosterId', item_id, 'multiplicador', multiplicador, 'fechaFin', fin);

  elsif tipo = 'cosmetico' then
    item_id := coalesce(nullif(cfg->>'cosmetico_id', ''), producto.slug);
    item_tipo := coalesce(nullif(cfg->>'item_tipo', ''), 'fondo');
    item_rareza := coalesce(nullif(cfg->>'rareza', ''), 'Normal');
    if item_rareza = 'Prohibido' then
      item_rareza := 'Mitico';
    end if;
    if item_rareza not in ('Normal', 'Raro', 'Epico', 'Legendario', 'Mitico') then
      item_rareza := 'Normal';
    end if;

    insert into public.usuario_cosmeticos (usuario_id, cosmetico_id, tipo, rareza, equipado)
    values (compra.usuario_id, item_id, item_tipo, item_rareza, false)
    on conflict (usuario_id, cosmetico_id) do update
      set tipo = excluded.tipo,
          rareza = excluded.rareza;

    entrega := jsonb_build_object('cosmeticoId', item_id, 'tipo', item_tipo, 'rareza', item_rareza);

  elsif tipo = 'experiencia' then
    cantidad := greatest(0, coalesce((cfg->>'cantidad')::bigint, 0));
    if cantidad <= 0 then
      raise exception 'Config de experiencia invalida';
    end if;

    xp_resultado := public.admin_recompensa_aplicar_xp(compra.usuario_id, cantidad);
    entrega := jsonb_build_object('xp', cantidad, 'resultadoNivel', xp_resultado);

  else
    raise exception 'Tipo de producto no soportado: %', tipo;
  end if;

  insert into public.historial_entregas (compra_id, usuario_id, producto_id, tipo, resultado)
  values (compra.id, compra.usuario_id, compra.producto_id, producto.tipo, entrega);

  update public.compras
  set estado = 'entregado',
      delivered_at = now()
  where id = compra.id;

  return jsonb_build_object('ok', true, 'mensaje', 'Compra entregada.', 'entrega', entrega);
exception
  when others then
    return jsonb_build_object('ok', false, 'mensaje', 'No se pudo entregar la compra.', 'detalle', sqlerrm);
end;
$$;

revoke all on function public.tienda_entregar_compra_pagada(uuid) from public, anon, authenticated;

insert into public.productos_tienda (slug, nombre, descripcion, tipo, precio_cop, orden, reward_config)
values
  ('coins_1000', '1.000 monedas', 'Paquete pequeno de monedas normales.', 'monedas', 3900, 10, '{"cantidad":1000}'::jsonb),
  ('coins_2500', '2.500 monedas', 'Paquete base de monedas normales.', 'monedas', 7900, 20, '{"cantidad":2500}'::jsonb),
  ('coins_5000', '5.000 monedas', 'Paquete competitivo de monedas normales.', 'monedas', 15900, 30, '{"cantidad":5000}'::jsonb),
  ('coins_8000', '8.000 monedas', 'Paquete popular de monedas normales.', 'monedas', 23900, 40, '{"cantidad":8000}'::jsonb),
  ('coins_12000', '12.000 monedas', 'Paquete recomendado de monedas normales.', 'monedas', 35900, 50, '{"cantidad":12000}'::jsonb),
  ('coins_18000', '18.000 monedas', 'Paquete avanzado de monedas normales.', 'monedas', 51900, 60, '{"cantidad":18000}'::jsonb),
  ('coins_25000', '25.000 monedas', 'Paquete competitivo grande.', 'monedas', 67900, 70, '{"cantidad":25000}'::jsonb),
  ('coins_40000', '45.000 monedas', '40.000 monedas mas bono.', 'monedas', 99900, 80, '{"cantidad":40000,"bonus":5000}'::jsonb),
  ('coins_65000', '75.000 monedas', '65.000 monedas mas bono.', 'monedas', 159900, 90, '{"cantidad":65000,"bonus":10000}'::jsonb),
  ('coins_100000', '120.000 monedas', '100.000 monedas mas bono premium.', 'monedas', 239900, 100, '{"cantidad":100000,"bonus":20000}'::jsonb),

  ('vip_7d', 'VIP 7 dias', 'Acceso VIP corto.', 'vip', 11900, 210, '{"dias":7}'::jsonb),
  ('vip_30d', 'VIP 30 dias', 'Acceso VIP mensual.', 'vip', 35900, 220, '{"dias":30}'::jsonb),
  ('vip_90d', 'VIP 90 dias', 'Acceso VIP de temporada.', 'vip', 79900, 230, '{"dias":90}'::jsonb),
  ('vip_permanent', 'VIP permanente', 'Acceso VIP sin vencimiento.', 'vip', 199900, 240, '{"dias":null}'::jsonb),

  ('booster_xp15_6h', 'Booster XP x1.5 - 6h', 'Potenciador de experiencia.', 'booster_xp', 1900, 310, '{"booster_id":"xp15_6h","multiplicador":1.5,"duracion_minutos":360}'::jsonb),
  ('booster_xp2_24h', 'Booster XP x2 - 24h', 'Potenciador de experiencia.', 'booster_xp', 7900, 320, '{"booster_id":"xp2_24h","multiplicador":2,"duracion_minutos":1440}'::jsonb),
  ('booster_xp2_3d', 'Booster XP x2 - 3d', 'Potenciador de experiencia.', 'booster_xp', 15900, 330, '{"booster_id":"xp2_3d","multiplicador":2,"duracion_minutos":4320}'::jsonb),
  ('booster_xp25_7d', 'Booster XP x2.5 - 7d', 'Potenciador de experiencia.', 'booster_xp', 27900, 340, '{"booster_id":"xp25_7d","multiplicador":2.5,"duracion_minutos":10080}'::jsonb),
  ('booster_xp3_7d', 'Booster XP x3 - 7d', 'Potenciador de experiencia.', 'booster_xp', 39900, 350, '{"booster_id":"xp3_7d","multiplicador":3,"duracion_minutos":10080}'::jsonb),
  ('booster_xp3_15d', 'Booster XP x3 - 15d', 'Potenciador de experiencia.', 'booster_xp', 59900, 360, '{"booster_id":"xp3_15d","multiplicador":3,"duracion_minutos":21600}'::jsonb),
  ('booster_xp4_30d', 'Booster XP x4 - 30d', 'Potenciador de experiencia.', 'booster_xp', 79900, 370, '{"booster_id":"xp4_30d","multiplicador":4,"duracion_minutos":43200}'::jsonb),
  ('booster_xp5_30d', 'Booster XP x5 - 30d', 'Potenciador de experiencia.', 'booster_xp', 119900, 380, '{"booster_id":"xp5_30d","multiplicador":5,"duracion_minutos":43200}'::jsonb),
  ('booster_xp6_45d', 'Booster XP x6 - 45d', 'Potenciador de experiencia.', 'booster_xp', 159900, 390, '{"booster_id":"xp6_45d","multiplicador":6,"duracion_minutos":64800}'::jsonb),
  ('booster_xp8_60d', 'Booster XP x8 - 60d', 'Potenciador de experiencia.', 'booster_xp', 239900, 400, '{"booster_id":"xp8_60d","multiplicador":8,"duracion_minutos":86400}'::jsonb),

  ('booster_coins_boost12_24d', 'Impulso Monedas x1.2 - 24d', 'Potenciador de monedas.', 'booster_monedas', 19900, 410, '{"booster_id":"coins_boost12_24d","multiplicador":1.2,"duracion_minutos":34560}'::jsonb),
  ('booster_coins_boost13_18d', 'Impulso Monedas x1.3 - 18d', 'Potenciador de monedas.', 'booster_monedas', 17900, 420, '{"booster_id":"coins_boost13_18d","multiplicador":1.3,"duracion_minutos":25920}'::jsonb),
  ('booster_coins_boost15_12d', 'Impulso Monedas x1.5 - 12d', 'Potenciador de monedas.', 'booster_monedas', 23900, 430, '{"booster_id":"coins_boost15_12d","multiplicador":1.5,"duracion_minutos":17280}'::jsonb),
  ('booster_coins_boost14_3d', 'Impulso Monedas x1.4 - 3d', 'Potenciador de monedas.', 'booster_monedas', 9900, 440, '{"booster_id":"coins_boost14_3d","multiplicador":1.4,"duracion_minutos":4320}'::jsonb),
  ('booster_coins_boost18_2d', 'Impulso Monedas x1.8 - 2d', 'Potenciador de monedas.', 'booster_monedas', 13900, 450, '{"booster_id":"coins_boost18_2d","multiplicador":1.8,"duracion_minutos":2880}'::jsonb),
  ('booster_coins_boost27_8h', 'Impulso Monedas x2.7 - 8h', 'Potenciador de monedas.', 'booster_monedas', 17900, 460, '{"booster_id":"coins_boost27_8h","multiplicador":2.7,"duracion_minutos":480}'::jsonb),
  ('booster_coins_boost2_3h', 'Impulso Monedas x2 - 3h', 'Potenciador de monedas.', 'booster_monedas', 7900, 470, '{"booster_id":"coins_boost2_3h","multiplicador":2,"duracion_minutos":180}'::jsonb),
  ('booster_coins_boost22_2h', 'Impulso Monedas x2.2 - 2h', 'Potenciador de monedas.', 'booster_monedas', 9900, 480, '{"booster_id":"coins_boost22_2h","multiplicador":2.2,"duracion_minutos":120}'::jsonb),
  ('booster_coins_boost25_1h', 'Impulso Monedas x2.5 - 1h', 'Potenciador de monedas.', 'booster_monedas', 10900, 490, '{"booster_id":"coins_boost25_1h","multiplicador":2.5,"duracion_minutos":60}'::jsonb),
  ('booster_coins_boost3_1h', 'Impulso Monedas x3 - 1h', 'Potenciador de monedas.', 'booster_monedas', 13900, 500, '{"booster_id":"coins_boost3_1h","multiplicador":3,"duracion_minutos":60}'::jsonb)
on conflict (slug) do update
set nombre = excluded.nombre,
    descripcion = excluded.descripcion,
    tipo = excluded.tipo,
    precio_cop = excluded.precio_cop,
    orden = excluded.orden,
    reward_config = excluded.reward_config,
    activo = true,
    updated_at = now();
