create table if not exists public.salas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  codigo text not null unique,
  creador_id text not null,
  estado text not null default 'esperando',
  max_jugadores integer not null default 40,
  juego text,
  inicio_torneo timestamptz,
  fecha_fin timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint salas_estado_check check (estado in ('esperando', 'en_juego', 'finalizado')),
  constraint salas_juego_check check (
    juego is null or juego in (
      'ajedrez',
      'damas',
      'domino',
      'flashmind',
      'matematicas',
      'memoria',
      'numcatch',
      'sudoku'
    )
  ),
  constraint salas_max_jugadores_check check (max_jugadores between 1 and 40)
);

create table if not exists public.sala_jugadores (
  id bigint generated by default as identity primary key,
  sala_id bigint not null references public.salas(id) on delete cascade,
  usuario_id text not null,
  usuario text,
  puntos integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (sala_id, usuario_id)
);

create table if not exists public.solitario_resultados (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  usuario text not null,
  puntos integer not null default 0,
  victoria boolean not null default false,
  sala_id bigint references public.salas(id) on delete set null,
  origen text not null default 'nivel',
  juego text not null default 'nivel',
  created_at timestamptz not null default now(),
  constraint solitario_origen_check check (origen in ('nivel', 'sala'))
);

create table if not exists public.progreso_niveles (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  usuario text,
  nivel integer not null,
  juego text not null,
  completado boolean not null default false,
  puntaje integer not null default 0,
  tiempo integer,
  resultado jsonb,
  updated_at timestamptz not null default now(),
  unique (usuario_id, nivel)
);

-- Reparacion para instalaciones donde las tablas ya existian antes de esta version.
-- CREATE TABLE IF NOT EXISTS no agrega columnas nuevas a tablas existentes.
alter table public.salas
add column if not exists juego text;

alter table public.salas
add column if not exists inicio_torneo timestamptz;

alter table public.salas
add column if not exists fecha_fin timestamptz;

alter table public.solitario_resultados
add column if not exists usuario_id text;

alter table public.solitario_resultados
add column if not exists usuario text;

alter table public.solitario_resultados
add column if not exists puntos integer not null default 0;

alter table public.solitario_resultados
add column if not exists victoria boolean not null default false;

alter table public.solitario_resultados
add column if not exists sala_id bigint;

alter table public.solitario_resultados
add column if not exists origen text not null default 'nivel';

alter table public.solitario_resultados
add column if not exists juego text not null default 'nivel';

alter table public.solitario_resultados
add column if not exists created_at timestamptz not null default now();

alter table public.salas
drop constraint if exists salas_juego_check;

alter table public.salas
add constraint salas_juego_check
check (
  juego is null or juego in (
    'ajedrez',
    'damas',
    'domino',
    'flashmind',
    'matematicas',
    'memoria',
    'numcatch',
    'sudoku'
  )
);

alter table public.solitario_resultados
drop constraint if exists solitario_origen_check;

alter table public.solitario_resultados
add constraint solitario_origen_check check (origen in ('nivel', 'sala'));

create index if not exists salas_codigo_idx on public.salas (codigo);
create index if not exists sala_jugadores_sala_id_idx on public.sala_jugadores (sala_id);
create index if not exists solitario_resultados_usuario_idx on public.solitario_resultados (usuario_id);
create index if not exists solitario_resultados_created_idx on public.solitario_resultados (created_at);
create index if not exists progreso_niveles_usuario_idx on public.progreso_niveles (usuario_id);

alter table public.salas enable row level security;
alter table public.sala_jugadores enable row level security;
alter table public.solitario_resultados enable row level security;
alter table public.progreso_niveles enable row level security;

drop policy if exists salas_solitario_select on public.salas;
drop policy if exists salas_solitario_insert on public.salas;
drop policy if exists salas_solitario_update on public.salas;

create policy salas_solitario_select on public.salas
for select to anon, authenticated using (true);

create policy salas_solitario_insert on public.salas
for insert to anon, authenticated with check (true);

create policy salas_solitario_update on public.salas
for update to anon, authenticated using (true) with check (true);

drop policy if exists sala_jugadores_solitario_select on public.sala_jugadores;
drop policy if exists sala_jugadores_solitario_insert on public.sala_jugadores;
drop policy if exists sala_jugadores_solitario_update on public.sala_jugadores;

create policy sala_jugadores_solitario_select on public.sala_jugadores
for select to anon, authenticated using (true);

create policy sala_jugadores_solitario_insert on public.sala_jugadores
for insert to anon, authenticated with check (true);

create policy sala_jugadores_solitario_update on public.sala_jugadores
for update to anon, authenticated using (true) with check (true);

drop policy if exists solitario_resultados_select on public.solitario_resultados;
drop policy if exists solitario_resultados_insert on public.solitario_resultados;

create policy solitario_resultados_select on public.solitario_resultados
for select to anon, authenticated using (true);

create policy solitario_resultados_insert on public.solitario_resultados
for insert to anon, authenticated with check (true);

drop policy if exists progreso_niveles_select on public.progreso_niveles;
drop policy if exists progreso_niveles_insert on public.progreso_niveles;
drop policy if exists progreso_niveles_update on public.progreso_niveles;

create policy progreso_niveles_select on public.progreso_niveles
for select to anon, authenticated using (true);

create policy progreso_niveles_insert on public.progreso_niveles
for insert to anon, authenticated with check (true);

create policy progreso_niveles_update on public.progreso_niveles
for update to anon, authenticated using (true) with check (true);

grant select, insert, update on table public.salas to anon, authenticated;
grant select, insert, update on table public.sala_jugadores to anon, authenticated;
grant select, insert on table public.solitario_resultados to anon, authenticated;
grant select, insert, update on table public.progreso_niveles to anon, authenticated;

grant usage, select on sequence public.salas_id_seq to anon, authenticated;
grant usage, select on sequence public.sala_jugadores_id_seq to anon, authenticated;
grant usage, select on sequence public.solitario_resultados_id_seq to anon, authenticated;
grant usage, select on sequence public.progreso_niveles_id_seq to anon, authenticated;

do $$
begin
  begin
    alter publication supabase_realtime add table public.salas;
  exception
    when duplicate_object then null;
    when undefined_object then null;
  end;

  begin
    alter publication supabase_realtime add table public.sala_jugadores;
  exception
    when duplicate_object then null;
    when undefined_object then null;
  end;
end;
$$;
